<?php
/**
 * Plugin Name: Brandon Cities Levels for Woocommerce
 * Plugin URL: https://zyro.pro
 * Author: Batita Brandon (based on work by Ubong Obot)
 * Author URL: https://zyro.pro
 * Description: This plugin adds cities for shipping zones in Woocommerce for Cameroon
 * Version: 0.1.0
 * License: GPL2
 * License URL: https://www.gnu.org/licenses/gpl-2.0.txt
 * Text-domain: clw
 */

// Add Basic Plugin Security
defined('ABSPATH') or die;

add_filter('woocommerce_states', 'cameroon_clw');

function cameroon_clw($states) {
    $map = array();

    $states_cameroon = array(
        'Yaoundé 1' => array(
            'Bastos' => 'Bastos',
            'Centre commercial' => 'Centre commercial',
            'Djoungolo II' => 'Djoungolo II',
            'Djoungolo III' => 'Djoungolo III',
            'Djoungolo IV' => 'Djoungolo IV',
            'Djoungolo IX' => 'Djoungolo IX',
            'Djoungolo V' => 'Djoungolo V',
            'Djoungolo VI' => 'Djoungolo VI',
            'Djoungolo VII' => 'Djoungolo VII',
            'Djoungolo VIII' => 'Djoungolo VIII',
            'Djoungolo X' => 'Djoungolo X',
            'Djoungolo XI' => 'Djoungolo XI',
            'Djoungolo XII' => 'Djoungolo XII',
            'Djoungololo I' => 'Djoungololo I',
            'Emana' => 'Emana',
            'Elig-Edzoa' => 'Elig-Edzoa',
            'Ekombitié' => 'Ekombitié',
            'Etoa-Meki' => 'Etoa-Meki',
            'Manguier' => 'Manguier',
            'Mballa I' => 'Mballa I',
            'Mballa II' => 'Mballa II',
            'Mballa III' => 'Mballa III',
            'Mballa IV' => 'Mballa IV',
            'Mballa V' => 'Mballa V',
            'Mballa VI' => 'Mballa VI',
            'Mballa VII' => 'Mballa VII',
            'Messassi' => 'Messassi',
            'Melen' => 'Melen',
            'Mfandena I' => 'Mfandena I',
            'Mfandena II' => 'Mfandena II',
            'Nkolmesseng' => 'Nkolmesseng',
            'Nkolodom III' => 'Nkolodom III',
            'Nkolondom I' => 'Nkolondom I',
            'Nkolondom II' => 'Nkolondom II',
            'Nlongkak' => 'Nlongkak',
            'Nlongkak I (préfecture)' => 'Nlongkak I (préfecture)',
            'Nlongkak II' => 'Nlongkak II',
            'Ngoulemakong' => 'Ngoulemakong',
            'Ngousso' => 'Ngousso',
            'Njon-essi' => 'Njon-essi',
            'Nylon I' => 'Nylon I',
            'Nylon II' => 'Nylon II',
            'Okolo' => 'Okolo',
            'Olembe I' => 'Olembe I',
            'Olembe II' => 'Olembe II',
            'Tongolo' => 'Tongolo',
            // Add more cities in Yaoundé 1 as needed
        ),
        'Yaoundé 2' => array(
            'Azegue Messa Mezala' => 'Azegue Messa Mezala',
            'Briqueterie' => 'Briqueterie',
            'Cité Verte' => 'Cité Verte',
            'Doumassi' => 'Doumassi',
            'Ekoudou' => 'Ekoudou',
            'Etetack Abobo' => 'Etetack Abobo',
            'Febe' => 'Febe',
            'Grand Messa' => 'Grand Messa',
            'Madagascar' => 'Madagascar',
            'Melen' => 'Melen',
            'Messa Plateau' => 'Messa Plateau',
            'Messa-Carrière' => 'Messa-Carrière',
            'Mokolo marché' => 'Mokolo marché',
            'Mokolo quartier' => 'Mokolo quartier',
            'Nkomkana I & III' => 'Nkomkana I & III',
            'Nkomkana II' => 'Nkomkana II',
            'Nlongkak' => 'Nlongkak',
            'Ntougou I' => 'Ntougou I',
            'Ntougou II' => 'Ntougou II',
            'Oliga' => 'Oliga',
            'Tsinga' => 'Tsinga',
            // Add more cities in Yaoundé 2 as needed
        ),
        'Yaoundé 3' => array(
            'Nlongkak' => 'Nlongkak',
            'Melen' => 'Melen',
            // Add the new information here in alphabetical order
            'Ahala 1' => 'Ahala 1',
            'Ahala 2' => 'Ahala 2',
            'Afanoya 1' => 'Afanoya 1',
            'Afanoya 2' => 'Afanoya 2',
            'Afanoya 3' => 'Afanoya 3',
            'Afanoya 4' => 'Afanoya 4',
            'Centre administratif, quartier du lac' => 'Centre administratif, quartier du lac',
            'Dakar I' => 'Dakar I',
            'Dakar II' => 'Dakar II',
            'Efoulan' => 'Efoulan',
            'Etoa' => 'Etoa',
            'Mbaligi' => 'Mbaligi',
            'Mekoumbou 1' => 'Mekoumbou 1',
            'Mekoumbou 2' => 'Mekoumbou 2',
            'Melen 1' => 'Melen 1',
            'Melen 2' => 'Melen 2',
            'Messong' => 'Messong',
            'Mvan' => 'Mvan',
            'Mvolyé' => 'Mvolyé',
            'Ngoa Ekélé' => 'Ngoa Ekélé',
            'Nkol-Mbenda' => 'Nkol-Mbenda',
            'Nkolmesseng' => 'Nkolmesseng',
            'Nkolfon' => 'Nkolfon',
            'Nsimeyong' => 'Nsimeyong',
            'Ntouessong' => 'Ntouessong',
            'Obili' => 'Obili',
            'Obobogo' => 'Obobogo',
            'Olezoa' => 'Olezoa',
            'Simbock' => 'Simbock',

            // Add more cities in Yaoundé 3 as needed
        ),
        'Yaoundé 4' => array(
            'Abome' => 'Abome',
            'Anguissa' => 'Anguissa',
            'Awae I' => 'Awae I',
            'Awae II' => 'Awae II',
            'Awae III' => 'Awae III',
            'Awae IV' => 'Awae IV',
            'Awae V' => 'Awae V',
            'Awae VI' => 'Awae VI',
            'Biteng' => 'Biteng',
            'Centre' => 'Centre',
            'Ekounou I' => 'Ekounou I',
            'Ekounou II-Nord' => 'Ekounou II-Nord',
            'Ekounou II-Sud' => 'Ekounou II-Sud',
            'Ekounou III' => 'Ekounou III',
            'Ekounou IV' => 'Ekounou IV',
            'Ekoumdoum' => 'Ekoumdoum',
            'Ekie-Nord' => 'Ekie-Nord',
            'Ekie-Sud' => 'Ekie-Sud',
            'Ekonou' => 'Ekonou',
            'Est' => 'Est',
            'Ewonkan' => 'Ewonkan',
            'Kondengui I-Est' => 'Kondengui I-Est',
            'Kondengui I-Ouest' => 'Kondengui I-Ouest',
            'Kondengui II' => 'Kondengui II',
            'Kondengui III' => 'Kondengui III',
            'Kondengui IV' => 'Kondengui IV',
            'Kondengui V' => 'Kondengui V',
            'Mbog Abang' => 'Mbog Abang',
            'Messamendongo' => 'Messamendongo',
            'Mfoundassi I' => 'Mfoundassi I',
            'Mfoundassi II' => 'Mfoundassi II',
            'Mfoundassi III' => 'Mfoundassi III',
            'Mimboman I-Centre' => 'Mimboman I-Centre',
            'Mimboman I-Est' => 'Mimboman I-Est',
            'Mimboman I-Sud' => 'Mimboman I-Sud',
            'Mimboman II' => 'Mimboman II',
            'Mimboman II-Nord' => 'Mimboman II-Nord',
            'Mimboman II-Sud' => 'Mimboman II-Sud',
            'Mimboman III' => 'Mimboman III',
            'Mimboman Plateau' => 'Mimboman Plateau',
            'Minkan' => 'Minkan',
            'Mvan-Nord' => 'Mvan-Nord',
            'Mvan-Sud' => 'Mvan-Sud',
            'Mvog Mbi' => 'Mvog Mbi',
            'Meyo' => 'Meyo',
            'Ndamvout' => 'Ndamvout',
            'Nkolndongo I' => 'Nkolndongo I',
            'Nkolndongo II' => 'Nkolndongo II',
            'Nkolndongo III' => 'Nkolndongo III',
            'Nkolndongo IV' => 'Nkolndongo IV',
            'Nkolndongo V' => 'Nkolndongo V',
            'Nkolndongo VI' => 'Nkolndongo VI',
            'Nkolndongo VII' => 'Nkolndongo VII',
            'Nkolndongo VIII' => 'Nkolndongo VIII',
            'Nkolndongo IX' => 'Nkolndongo IX',
            'Nkolndongo X' => 'Nkolndongo X',
            'Nkolndongo XI' => 'Nkolndongo XI',
            'Nkolndongo XII' => 'Nkolndongo XII',
            'Nkolndongo XIII' => 'Nkolndongo XIII',
            'Nkolndongo XIV' => 'Nkolndongo XIV',
            'Nkolo' => 'Nkolo',
            'Nkomo I' => 'Nkomo I',
            'Nkomo II-Nord' => 'Nkomo II-Nord',
            'Nkomo II-Sud' => 'Nkomo II-Sud',
            'Nord' => 'Nord',
            'Ntouessong' => 'Ntouessong',
            'Odza I' => 'Odza I',
            'Odza II' => 'Odza II',
            'Odza III' => 'Odza III',
            'Ouest' => 'Ouest',
            'Simbock' => 'Simbock',
            'Sud' => 'Sud',
            'Toutouli' => 'Toutouli',
            'Tropicana' => 'Tropicana',
            'Mvan-Nord' => 'Mvan-Nord',
            'Mvan-Sud' => 'Mvan-Sud',
            // Add more cities in Yaoundé 4 as needed
        ),
        'Yaoundé 5' => array(
            'Eleveur' => 'Eleveur',
            'Essos Centre' => 'Essos Centre',
            'Essos Nord' => 'Essos Nord',
            'Essos Sud' => 'Essos Sud',
            'Mfandena' => 'Mfandena',
            'Mvog-Ada' => 'Mvog-Ada',
            'Ngoulmekong' => 'Ngoulmekong',
            'Ngousso Djougolo IV' => 'Ngousso Djougolo IV',
            'Ngousso Djougolo V' => 'Ngousso Djougolo V',
            'Ngousso Djougolo VI' => 'Ngousso Djougolo VI',
            'Ngousso Djougolo VII' => 'Ngousso Djougolo VII',
            'Ngousso Djougolo VIII' => 'Ngousso Djougolo VIII',
            'Ngousso Djougolo IX' => 'Ngousso Djougolo IX',
            'Ngousso Djougolo X' => 'Ngousso Djougolo X',
            'Ngousso Djougolo XI' => 'Ngousso Djougolo XI',
            'Ngousso Djougolo XII' => 'Ngousso Djougolo XII',
            'Nkolmesseng' => 'Nkolmesseng',
            'Quartier Fouda' => 'Quartier Fouda',
            'Ngousso-Ntem' => 'Ngousso-Ntem',
            // Add more cities in Yaoundé 5 as needed
        ),
        'Yaoundé 6' => array(
            'Biyem-Assi' => 'Biyem-Assi',
            'Eba Biyem-Assi' => 'Eba Biyem-Assi',
            'Etoug-Ebe I' => 'Etoug-Ebe I',
            'Etoug-Ebe II' => 'Etoug-Ebe II',
            'Melen I' => 'Melen I',
            'Melen III' => 'Melen III',
            'Melen IV' => 'Melen IV',
            'Melen V' => 'Melen V',
            'Melen VI' => 'Melen VI',
            'Melen VIIA' => 'Melen VIIA',
            'Melen VIIB' => 'Melen VIIB',
            'Melen VIIIC' => 'Melen VIIIC',
            'Melen IX' => 'Melen IX',
            'Mvog-Betsi' => 'Mvog-Betsi',
            'Mendong Camp Sic' => 'Mendong Camp Sic',
            'Nkolbikok I' => 'Nkolbikok I',
            'Nkolbikok II' => 'Nkolbikok II',
            'Simbock' => 'Simbock',
            // Add more cities in Yaoundé 6 as needed
        ),
        'Yaoundé 7' => array(
            'Abobo' => 'Abobo',
            'Ebot-Mefou' => 'Ebot-Mefou',
            'Etetak' => 'Etetak',
            'Mbog-Doum' => 'Mbog-Doum',
            'Ndamvouth' => 'Ndamvouth',
            'Nkol-So' => 'Nkol-So',
            'Nkolbisson' => 'Nkolbisson',
            'Nkomassi' => 'Nkomassi',
            'Nnom-Nnam' => 'Nnom-Nnam',
            'Ngoulemakong' => 'Ngoulemakong',
            'Nkolbikok II' => 'Nkolbikok II',
            'Oyom Abang I' => 'Oyom Abang I',
            'Oyom Abang II' => 'Oyom Abang II',
            'Oyom Abang III' => 'Oyom Abang III',
            'Oyom Abang IV' => 'Oyom Abang IV',
            // Add more cities in Yaoundé 7 as needed

        ),
        'Douala I' => array(
            'Akwa' => 'Akwa',
            'Bali' => 'Bali',
            'Bessengue' => 'Bessengue',
            'Bonamikengué' => 'Bonamikengué',
            'Bonamoudourou' => 'Bonamoudourou',
            'Bonabékombo' => 'Bonabékombo',
            'Bonamouti-Akwa 2' => 'Bonamouti-Akwa 2',
            'Bonadibong' => 'Bonadibong',
            'Bonamouti-Deido' => 'Bonamouti-Deido',
            'Bonadouma' => 'Bonadouma',
            'Bonanjo' => 'Bonanjo',
            'Bonadoumbè' => 'Bonadoumbè',
            'Bonapriso' => 'Bonapriso',
            'Bonajinjè' => 'Bonajinjè',
            'Bonatéki' => 'Bonatéki',
            'Bonakouamouang' => 'Bonakouamouang',
            'Bonaténè' => 'Bonaténè',
            'Bonalembè' => 'Bonalembè',
            'Bonantonè' => 'Bonantonè',
            'Bonajang' => 'Bonajang',
            'Hydrocarbures' => 'Hydrocarbures',
            'Bonelang' => 'Bonelang',
            'Joss' => 'Joss',
            'Bonalékè' => 'Bonalékè',
            'Koumassi' => 'Koumassi',
            'Bonakeke Akwa' => 'Bonakeke Akwa',
            'Ngodi' => 'Ngodi',
            'Grand Moulin' => 'Grand Moulin',
            'Nkongmondo' => 'Nkongmondo',
            'Nouvelle zone d\'Akwa Nord' => 'Nouvelle zone d\'Akwa Nord',
            'Nouvelle zone de New-Deido' => 'Nouvelle zone de New-Deido'
            // Add more districts in Douala I as needed
        ),
        'Douala II' => array(
            'Aéroport' => 'Aéroport',
            'Babylone I' => 'Babylone I',
            'Babylone II' => 'Babylone II',
            'Bonadouma' => 'Bonadouma',
            'Congo' => 'Congo',
            'Kassalafam' => 'Kassalafam',
            'Lagos Market' => 'Lagos Market',
            'Lycée de New-Bell' => 'Lycée de New-Bell',
            'Mbam Ewondo' => 'Mbam Ewondo',
            'Ndjong-Mebi' => 'Ndjong-Mebi',
            'Nkololoum' => 'Nkololoum',
            'Ngangue' => 'Ngangue',
            'Prison' => 'Prison',
            'Sabenjongo' => 'Sabenjongo',
            'Source, T.S.F.' => 'Source, T.S.F.',
            'Youpwé' => 'Youpwé'
            // Add more districts in Douala II as needed
        ),
        'Douala III' => array(
            'Bilongue I' => 'Bilongue I',
            'Bilongue II' => 'Bilongue II',
            'Bonanloka' => 'Bonanloka',
            'Brazzaville' => 'Brazzaville',
            'Newtown aéroport' => 'Newtown aéroport',
            'Bwang' => 'Bwang',
            'Cité de la Paix' => 'Cité de la Paix',
            'Cité des Enseignants' => 'Cité des Enseignants',
            'Dibom I' => 'Dibom I',
            'Dibom II' => 'Dibom II',
            'Japoma' => 'Japoma',
            'Logbaba' => 'Logbaba',
            'Logbessou' => 'Logbessou',
            'Madagascar' => 'Madagascar',
            'Mbanga Mpongo' => 'Mbanga Mpongo',
            'RNCFC' => 'RNCFC',
            'Ndogbatti CDP' => 'Ndogbatti CDP',
            'Ndoghem I' => 'Ndoghem I',
            'Ndoghem II' => 'Ndoghem II',
            'Ndogmbe' => 'Ndogmbe',
            'Ndokoti' => 'Ndokoti',
            'Ndogbong' => 'Ndogbong',
            'CCC' => 'CCC',
            'Ndogpassi I' => 'Ndogpassi I',
            'Ndogpassi II' => 'Ndogpassi II',
            'Logmayangui' => 'Logmayangui',
            'Cité des Billes' => 'Cité des Billes',
            'Ari' => 'Ari',
            'Mboko' => 'Mboko',
            'Nkôlmbong' => 'Nkôlmbong',
            'Ndodi' => 'Ndodi',
            'Ngoma' => 'Ngoma',
            'Nyalla' => 'Nyalla',
            'Nylon' => 'Nylon',
            'Oyack' => 'Oyack',
            'P.K.8' => 'P.K.8',
            'P.K.12' => 'P.K.12',
            'P.K.14' => 'P.K.14',
            'P.K.17' => 'P.K.17',
            'P.K.19' => 'P.K.19',
            'P.K.21' => 'P.K.21',
            'P.K.J.6' => 'P.K.J.6',
            'Soboum' => 'Soboum',
            'Tergal' => 'Tergal',
            'Yansoki' => 'Yansoki',
            'Yassa' => 'Yassa',
            'Yatchika' => 'Yatchika',
            'Yonyong' => 'Yonyong',
            'Ngodi bakoko' => 'Ngodi bakoko'
            // Add more districts in Douala III as needed
        ),
        'Douala IV' => array(
            'Bonendale 2' => 'Bonendale 2',
            'Besseke' => 'Besseke',
            'Bilingue' => 'Bilingue',
            'Bonamatoumbe Ville' => 'Bonamatoumbe Ville',
            'Bonambappé' => 'Bonambappé',
            'Bonaminkano' => 'Bonaminkano',
            'Bonassama' => 'Bonassama',
            'Grand Hangar' => 'Grand Hangar',
            'Mambanda' => 'Mambanda',
            'Ndobo' => 'Ndobo',
            'Ngwele' => 'Ngwele',
            'Nkomba' => 'Nkomba',
            'Sodiko Ville' => 'Sodiko Ville',
            'Bojongo' => 'Bojongo',
            'Bonamatoumbe Village' => 'Bonamatoumbe Village',
            'Bonendale I' => 'Bonendale I',
            'Bonendale II' => 'Bonendale II',
            'Djébalè I' => 'Djébalè I',
            'Djébalè II' => 'Djébalè II',
            'Sodiko Village' => 'Sodiko Village'
            // Add more districts in Douala IV as needed
        ),
        'Douala V' => array(
            'Bépanda Bonamoussongo' => 'Bépanda Bonamoussongo',
            'Bépanda Bonéwanda' => 'Bépanda Bonéwanda',
            'Bépanda Omnisports' => 'Bépanda Omnisports',
            'Bépanda Petit Wouri' => 'Bépanda Petit Wouri',
            'Bépanda TSF Cacao Barry' => 'Bépanda TSF Cacao Barry',
            'Bépanda TSF' => 'Bépanda TSF',
            'Bépanda Voirie' => 'Bépanda Voirie',
            'Bépanda Yonyong' => 'Bépanda Yonyong',
            'Bonamoussadi Cité' => 'Bonamoussadi Cité',
            'Cacao Barry' => 'Cacao Barry',
            'Cité des Palmiers' => 'Cité des Palmiers',
            'Cité Makepé' => 'Cité Makepé',
            'Cité Sic' => 'Cité Sic',
            'Dikahe (PK10)' => 'Dikahe (PK10)',
            'Emene City' => 'Emene City',
            'Gentil' => 'Gentil',
            'Jourdain' => 'Jourdain',
            'Kondi PK8' => 'Kondi PK8',
            'Makèpè Maturité' => 'Makèpè Maturité',
            'Makèpè Petit Pays' => 'Makèpè Petit Pays',
            'Makèpè Recasement' => 'Makèpè Recasement',
            'Makèpè Terminus' => 'Makèpè Terminus',
            'Manikè' => 'Manikè',
            'Mbenguè City' => 'Mbenguè City',
            'Nguereck' => 'Nguereck',
            'PK 15' => 'PK 15',
            'PK 16' => 'PK 16',
            'PK 17' => 'PK 17',
            'PK 21' => 'PK 21',
            'Sobikago' => 'Sobikago',
            'Sodikombo' => 'Sodikombo'
            // Add more districts in Douala V as needed
        ),
        'Douala VI' => array(
            'Manoka Island' => 'Manoka Island',
            'Manoka' => 'Manoka',
            'Dahomey' => 'Dahomey',
            'Number One Creek' => 'Number One Creek',
            'Nyangadou' => 'Nyangadou',
            'Mbénadikoumé' => 'Mbénadikoumé',
            'Epaka I' => 'Epaka I',
            'Epaka II' => 'Epaka II',
            'Buea I' => 'Buea I',
            'Wouri bank in Douala from an aerial view' => 'Wouri bank in Douala from an aerial view',
            'Right bank of the Wouri' => 'Right bank of the Wouri',
            'Bessoukoudou' => 'Bessoukoudou',
            'Bwapé' => 'Bwapé',
            'Moukala Tanda' => 'Moukala Tanda',
            'Kombo' => 'Kombo',
            'Bouma' => 'Bouma',
            'Moungangué' => 'Moungangué',
            'Kombo Moukoko (Moundjou Island)' => 'Kombo Moukoko (Moundjou Island)',
            'Poka I' => 'Poka I',
            'Akra Kombo' => 'Akra Kombo',
            'Cap Cameroun' => 'Cap Cameroun',
            'Petit Toubé' => 'Petit Toubé',
            'Left bank of the Wouri' => 'Left bank of the Wouri',
            'Bikoro' => 'Bikoro',
            'Koo' => 'Koo',
            'Missipi' => 'Missipi',
            'Matanda Massadi' => 'Matanda Massadi'
            // Add more districts in Douala VI as needed
        ),
        'Bangem' => array(
            'Ballock' => 'Ballock',
            'Boka' => 'Boka',
            'Ebase' => 'Ebase',
            'Ebonemin' => 'Ebonemin',
            'Ekambeng' => 'Ekambeng',
            'Ekangte' => 'Ekangte',
            'Elase' => 'Elase',
            'Enyandong' => 'Enyandong',
            'Epen' => 'Epen',
            'Epenebel' => 'Epenebel',
            'Mbat' => 'Mbat',
            'Mombo' => 'Mombo',
            'Muabi' => 'Muabi',
            'Muagwekan' => 'Muagwekan',
            'Muaku' => 'Muaku',
            'Muandon' => 'Muandon',
            'Muanenguba' => 'Muanenguba',
            'Muantah' => 'Muantah',
            'Muanyet' => 'Muanyet',
            'Muaone' => 'Muaone',
            'Muasum' => 'Muasum',
            'Muebah' => 'Muebah',
            'Muekan' => 'Muekan',
            'Muelong' => 'Muelong',
            'Muesok' => 'Muesok',
            'Muetan-Aku' => 'Muetan-Aku',
            'Ndibse II' => 'Ndibse II',
            'Ngomin' => 'Ngomin',
            'Njandu' => 'Njandu',
            'Njom' => 'Njom',
            'Nkang' => 'Nkang',
            'Nkikoh' => 'Nkikoh',
            'Nkongte' => 'Nkongte',
            'Nteho' => 'Nteho',
            'Nyan' => 'Nyan',
            'Nzimbeng' => 'Nzimbeng',
            'Poala' => 'Poala',
            'Tare' => 'Tare'

            // Add more districts in buea as needed
        ),
        'Nguti' => array(
            'Ayong' => 'Ayong',
            'Babensi' => 'Babensi',
            'Babubock' => 'Babubock',
            'Badun' => 'Badun',
            'Bambe' => 'Bambe',
            'Bajange' => 'Bajange',
            'Baro' => 'Baro',
            'Bermin' => 'Bermin',
            'Betock' => 'Betock',
            'Bombe Konye' => 'Bombe Konye',
            'Dinte' => 'Dinte',
            'Ebanga' => 'Ebanga',
            'Ediengo Banyu' => 'Ediengo Banyu',
            'Ediengoh' => 'Ediengoh',
            'Ehunyampe' => 'Ehunyampe',
            'Ekenge' => 'Ekenge',
            'Ekita' => 'Ekita',
            'Ekona Babeti' => 'Ekona Babeti',
            'Ekwenjo' => 'Ekwenjo',
            'Elumba' => 'Elumba',
            'Esime Mudip' => 'Esime Mudip',
            'Etawang' => 'Etawang',
            'Etodi' => 'Etodi',
            'Fonki' => 'Fonki',
            'Fowung' => 'Fowung',
            'Kamalumpe' => 'Kamalumpe',
            'Lebeh' => 'Lebeh',
            'Lekwe' => 'Lekwe',
            'Manyemen' => 'Manyemen',
            'Mbetta' => 'Mbetta',
            'Mboka' => 'Mboka',
            'Mungo Ndor' => 'Mungo Ndor',
            'New Konye' => 'New Konye',
            'Njentu' => 'Njentu',
            'Njuinyue' => 'Njuinyue',
            'Njungo' => 'Njungo',
            'Nkwenfor' => 'Nkwenfor',
            'Nloh' => 'Nloh',
            'Nongomadiba' => 'Nongomadiba',
            'Ntale' => 'Ntale',
            'Nzelleted' => 'Nzelleted',
            'Nzoa' => 'Nzoa',
            'Nzobi' => 'Nzobi',
            'Ofrikpabi' => 'Ofrikpabi',
            'Osirayib' => 'Osirayib',
            'Sikam' => 'Sikam',
            'Songlo' => 'Songlo',
            'Tabongkwa' => 'Tabongkwa',
            'Talangaye' => 'Talangaye',
            'Tang' => 'Tang',

            // Add more districts in buea as needed
        ),
        'Tombel' => array(
            'Atob' => 'Atob',
            'Bambele' => 'Bambele',
            'Bajoh' => 'Bajoh',
            'Bakolle' => 'Bakolle',
            'Bangone' => 'Bangone',
            'Baseng' => 'Baseng',
            'Bekume' => 'Bekume',
            'Bendume' => 'Bendume',
            'Buba ou Bouba' => 'Buba ou Bouba',
            'Bulutu' => 'Bulutu',
            'Ebome' => 'Ebome',
            'Ebonji' => 'Ebonji',
            'Ebubu' => 'Ebubu',
            'Edib ou Edibe' => 'Edib ou Edibe',
            'Edipinjock' => 'Edipinjock',
            'Ehom' => 'Ehom',
            'Ekeb' => 'Ekeb',
            'Etam' => 'Etam',
            'Etanenbu' => 'Etanenbu',
            'Eyange' => 'Eyange',
            'Douala Makambo' => 'Douala Makambo',
            'Kack' => 'Kack',
            'Kodmin' => 'Kodmin',
            'Kola' => 'Kola',
            'Kupe' => 'Kupe',
            'Mbabe' => 'Mbabe',
            'Mahole' => 'Mahole',
            'Mbogmut' => 'Mbogmut',
            'Mbomekoged' => 'Mbomekoged',
            'Mbule ou Mbulle' => 'Mbule ou Mbulle',
            'Mekedmbeng' => 'Mekedmbeng',
            'Mekom' => 'Mekom',
            'Melongo' => 'Melongo',
            'Menge' => 'Menge',
            'Menyom' => 'Menyom',
            'Mesaka' => 'Mesaka',
            'Mpako I' => 'Mpako I',
            'Mpako II' => 'Mpako II',
            'Muahunembeng' => 'Muahunembeng',
            'Muayam' => 'Muayam',
            'Muasong' => 'Muasong',
            'Muyuka' => 'Muyuka',
            'Ndibenjock' => 'Ndibenjock',
            'Ndisi' => 'Ndisi',
            'Ndom' => 'Ndom',
            'Ngomboku' => 'Ngomboku',
            'Ngombombeng' => 'Ngombombeng',
            'Ngusi' => 'Ngusi',
            'Nhiangse' => 'Nhiangse',
            'Nlog' => 'Nlog',
            'Nsoke ou Nsuke' => 'Nsoke ou Nsuke',
            'Nyalle' => 'Nyalle',
            'Nyandong' => 'Nyandong',
            'Nyasoso' => 'Nyasoso',
            'Peng' => 'Peng',
            'Yorge' => 'Yorge'

            // Add more districts in buea as needed
        ),
        'Alou' => array(
            'Attrah' => 'Attrah',
            'Fonjumetaw' => 'Fonjumetaw',
            'Lewoh' => 'Lewoh',
            'M\'mouck' => 'M\'mouck',
            'M\'mouckbie' => 'M\'mouckbie',
            'Ndugatet' => 'Ndugatet',
            'Nwangong' => 'Nwangong'

            // Add more districts in buea as needed
        ),
        'Menji' => array(
            'Essoh Attah' => 'Essoh Attah',
            'Fotabong III' => 'Fotabong III',
            'Lebang' => 'Lebang',
            'Mbiandia' => 'Mbiandia'

            // Add more districts in buea as needed
        ),
        'Wabane' => array(
            'Bamumbu' => 'Bamumbu',
            'Bangang' => 'Bangang',
            'Banti' => 'Banti',
            'Bechati' => 'Bechati',
            'Besali' => 'Besali',
            'Egumbo ou Igumba' => 'Egumbo ou Igumba',
            'Folepi' => 'Folepi',
            'Fomenji' => 'Fomenji',
            'Nkong' => 'Nkong'

            // Add more districts in buea as needed
        ),
        'Akwaya' => array(
            'Abonando' => 'Abonando',
            'Akuruawe' => 'Akuruawe',
            'Akwa' => 'Akwa',
            'Alunfa' => 'Alunfa',
            'Amanavil' => 'Amanavil',
            'Amassi' => 'Amassi',
            'Amayo' => 'Amayo',
            'Ameh' => 'Ameh',
            'Anomoginge' => 'Anomoginge',
            'Ashunda' => 'Ashunda',
            'Assaka' => 'Assaka',
            'Assam' => 'Assam',
            'Atolo' => 'Atolo',
            'Ayi' => 'Ayi',
            'Bachama' => 'Bachama',
            'Bache' => 'Bache',
            'Badjie' => 'Badjie',
            'Bagundu' => 'Bagundu',
            'Bakem' => 'Bakem',
            'Bakinjaw' => 'Bakinjaw',
            'Ballin' => 'Ballin',
            'Banguh' => 'Banguh',
            'Bantakpa' => 'Bantakpa',
            'Barombochi' => 'Barombochi',
            'Basho I' => 'Basho I',
            'Basho II' => 'Basho II',
            'Batabi' => 'Batabi',
            'Beteme' => 'Beteme',
            'Bodam' => 'Bodam',
            'Boka' => 'Boka',
            'Bombe' => 'Bombe',
            'Chikpa' => 'Chikpa',
            'Dadi' => 'Dadi',
            'Ebinsi' => 'Ebinsi',
            'Enjawbaw' => 'Enjawbaw',
            'Eshobi Bajou' => 'Eshobi Bajou',
            'Kajifu I' => 'Kajifu I',
            'Kajifu II' => 'Kajifu II',
            'Kajinga' => 'Kajinga',
            'Kalumu' => 'Kalumu',
            'Kateli' => 'Kateli',
            'Kekpani' => 'Kekpani',
            'Kekukesim I' => 'Kekukesim I',
            'Kekukesim II' => 'Kekukesim II',
            'Keluo' => 'Keluo',
            'Kenchi' => 'Kenchi',
            'Kesham' => 'Kesham',
            'Ketoya' => 'Ketoya',
            'Kunku' => 'Kunku',
            'Manko' => 'Manko',
            'Matene' => 'Matene',
            'Mbu' => 'Mbu',
            'Mbulu' => 'Mbulu',
            'Meyerim' => 'Meyerim',
            'Motom' => 'Motom',
            'Mukonyong' => 'Mukonyong',
            'Nchumba' => 'Nchumba',
            'Nfakwe' => 'Nfakwe',
            'Nga' => 'Nga',
            'Ngali' => 'Ngali',
            'Nkunsu' => 'Nkunsu',
            'Ntameli' => 'Ntameli',
            'Obonyi I' => 'Obonyi I',
            'Obonyi II' => 'Obonyi II',
            'Obonyi III' => 'Obonyi III',
            'Okpambe' => 'Okpambe',
            'Olulu' => 'Olulu',
            'Ossato' => 'Ossato',
            'Otongo' => 'Otongo',
            'Takamanda' => 'Takamanda',
            'Takwo' => 'Takwo',
            'Tambu' => 'Tambu',
            'Tassomo' => 'Tassomo',
            'Tava' => 'Tava',
            'Tinta' => 'Tinta',
            'Ugbakan' => 'Ugbakan',
            'Yive' => 'Yive'

            // Add more districts in buea as needed
        ),
        'Eyumodjock' => array(
            'Abat' => 'Abat',
            'Afap' => 'Afap',
            'Agborkem' => 'Agborkem',
            'Ajaman' => 'Ajaman',
            'Ajayukndip' => 'Ajayukndip',
            'Akak' => 'Akak',
            'Akwen' => 'Akwen',
            'Araru' => 'Araru',
            'Ayaoke' => 'Ayaoke',
            'Ayukaba' => 'Ayukaba',
            'Babi' => 'Babi',
            'Babong' => 'Babong',
            'Bajoh' => 'Bajoh',
            'Bakogo' => 'Bakogo',
            'Bakut' => 'Bakut',
            'Bakwelle' => 'Bakwelle',
            'Bayenti' => 'Bayenti',
            'Bayib-Arsibong' => 'Bayib-Arsibong',
            'Bayib-Ossing' => 'Bayib-Ossing',
            'Ebam' => 'Ebam',
            'Ebinsi' => 'Ebinsi',
            'Ekogate' => 'Ekogate',
            'Ekok' => 'Ekok',
            'Etinkem' => 'Etinkem',
            'Ewelle' => 'Ewelle',
            'Eyang-Amanghe' => 'Eyang-Amanghe',
            'Inokun' => 'Inokun',
            'Kembong' => 'Kembong',
            'Mbakang' => 'Mbakang',
            'Mbakem' => 'Mbakem',
            'Mbatop' => 'Mbatop',
            'Mbenyan' => 'Mbenyan',
            'Mbinda-Tabo' => 'Mbinda-Tabo',
            'Mbufong' => 'Mbufong',
            'Mfumi' => 'Mfumi',
            'Mgbegati' => 'Mgbegati',
            'Mkpot' => 'Mkpot',
            'Ndebaya' => 'Ndebaya',
            'Ndekwai' => 'Ndekwai',
            'Njeke' => 'Njeke',
            'Nkimechi' => 'Nkimechi',
            'Nkogho' => 'Nkogho',
            'Nsanakang' => 'Nsanakang',
            'Nsanaragati' => 'Nsanaragati',
            'Ntenako' => 'Ntenako',
            'Ogomoko' => 'Ogomoko',
            'Okoroba' => 'Okoroba',
            'Okurikang' => 'Okurikang',
            'Onaku' => 'Onaku',
            'Osselle' => 'Osselle',
            'Ossing' => 'Ossing',
            'Otu' => 'Otu',
            'Taboh' => 'Taboh',
            'Talangaye' => 'Talangaye'

            // Add more districts in buea as needed
        ),
        'Central Mamfé' => array(
            'Bachuo Ntai' => 'Bachuo Ntai',
            'Besong Abang' => 'Besong Abang',
            'Besongabang' => 'Besongabang',
            'Egbekaw' => 'Egbekaw',
            'Eshobi' => 'Eshobi',
            'Etemetek' => 'Etemetek',
            'Eyangchang' => 'Eyangchang',
            'Eyangntui' => 'Eyangntui',
            'Mile One' => 'Mile One',
            'Nchang' => 'Nchang',
            'Okoyong' => 'Okoyong',
            'Nfaitock 2' => 'Nfaitock 2'

            // Add more districts in buea as needed
        ),
        'Upper Bayang' => array(
            'Adjeli' => 'Adjeli',
            'Agong' => 'Agong',
            'Akiriba' => 'Akiriba',
            'Amebisu' => 'Amebisu',
            'Ashum' => 'Ashum',
            'Atibong Wire' => 'Atibong Wire',
            'Ayukaba Betieku' => 'Ayukaba Betieku',
            'Babat' => 'Babat',
            'Bachuo Akagbe' => 'Bachuo Akagbe',
            'Batambe' => 'Batambe',
            'Bakebe' => 'Bakebe',
            'Bakumba Batieku' => 'Bakumba Batieku',
            'Bokwa' => 'Bokwa',
            'Chinda' => 'Chinda',
            'Defang' => 'Defang',
            'Ebangabi' => 'Ebangabi',
            'Ebeagwa' => 'Ebeagwa',
            'Ebensuk' => 'Ebensuk',
            'Edjuingang' => 'Edjuingang',
            'Egbemoh' => 'Egbemoh',
            'Ekpor' => 'Ekpor',
            'Etoko' => 'Etoko',
            'Etoko-Mbatop' => 'Etoko-Mbatop',
            'Eyang Atemako' => 'Eyang Atemako',
            'Fotabe' => 'Fotabe',
            'Gurrifen' => 'Gurrifen',
            'Kekpoti' => 'Kekpoti',
            'Kendem' => 'Kendem',
            'Kenyang' => 'Kenyang',
            'Kepelle' => 'Kepelle',
            'Koano' => 'Koano',
            'Mamboh' => 'Mamboh',
            'Mantah I' => 'Mantah I',
            'Mantah II' => 'Mantah II',
            'Mbanga-Pongo' => 'Mbanga-Pongo',
            'Mbeme' => 'Mbeme',
            'Mbinjong' => 'Mbinjong',
            'Mbio' => 'Mbio',
            'Mekwecha' => 'Mekwecha',
            'Moshie' => 'Moshie',
            'Nchemba I' => 'Nchemba I',
            'Nchemba II' => 'Nchemba II',
            'Nfainchang' => 'Nfainchang',
            'Nfaitock' => 'Nfaitock',
            'Ntenmbang' => 'Ntenmbang',
            'Numba' => 'Numba',
            'Obang 3 Corners' => 'Obang 3 Corners',
            'Sabes' => 'Sabes',
            'Sumbe' => 'Sumbe',
            'Tali I' => 'Tali I',
            'Tali II' => 'Tali II',
            'Tayor' => 'Tayor',
            'Tinto-Kerieh' => 'Tinto-Kerieh'

            // Add more districts in buea as needed
        ),
        'Konye' => array(
            'Besingi' => 'Besingi',
            'Choa' => 'Choa',
            'Maseke' => 'Maseke',
            'Mbanda' => 'Mbanda',
            'Mokongo' => 'Mokongo',
            'Ngolo Bolo' => 'Ngolo Bolo',
            'Baduma' => 'Baduma',
            'Bakumba' => 'Bakumba',
            'Bolo Moboka' => 'Bolo Moboka',
            'Dikomi' => 'Dikomi',
            'Dikoro' => 'Dikoro',
            'Dipenda' => 'Dipenda',
            'Ediki Mbonge' => 'Ediki Mbonge',
            'Ibemi' => 'Ibemi',
            'Ifanga I' => 'Ifanga I',
            'Ifanga II' => 'Ifanga II',
            'Ikiliwindi' => 'Ikiliwindi',
            'Illeh' => 'Illeh',
            'Itoki' => 'Itoki',
            'Koba' => 'Koba',
            'Kokaka' => 'Kokaka',
            'Kokobuma' => 'Kokobuma',
            'Kombone Bafaw' => 'Kombone Bafaw',
            'Kumbe' => 'Kumbe',
            'Kurume' => 'Kurume',
            'Lobange' => 'Lobange',
            'Lobongi' => 'Lobongi',
            'Makobe' => 'Makobe',
            'Matoh' => 'Matoh',
            'Matoh Butu' => 'Matoh Butu',
            'Matondo I' => 'Matondo I',
            'Matondo II' => 'Matondo II',
            'Mbakwa Supe' => 'Mbakwa Supe',
            'Mbombe' => 'Mbombe',
            'Mbonge Meteke' => 'Mbonge Meteke',
            'Mbu' => 'Mbu',
            'Mosanje' => 'Mosanje',
            'Mwangale' => 'Mwangale',
            'Sambaliba' => 'Sambaliba',
            'Weme' => 'Weme',
            'Wone' => 'Wone'

            // Add more districts in buea as needed
        ),
        'Kumba I' => array(
            'Barombi Mbo' => 'Barombi Mbo',
            'Kumba Mbeng Ekemba I' => 'Kumba Mbeng Ekemba I',
            'Administrative District' => 'Administrative District',
            'Kumba Mbeng Ekemba II' => 'Kumba Mbeng Ekemba II',
            'Kumba Njuki' => 'Kumba Njuki',
            'Monte Carlo' => 'Monte Carlo',
            'Kumba Njembe' => 'Kumba Njembe',
            'Kumba Mbeng Ekemue 1' => 'Kumba Mbeng Ekemue 1',
            'Makiti' => 'Makiti',
            'Kumba Mbeng Ekemue II' => 'Kumba Mbeng Ekemue II',
            'Makatol I' => 'Makatol I',
            'Nkake I Bongwana' => 'Nkake I Bongwana',
            'Makatol II' => 'Makatol II',
            'Mile On' => 'Mile On',
            'Makatol III' => 'Makatol III',
            'Njake II' => 'Njake II',
            'Bokoko' => 'Bokoko',
            'Nkamundikum 1' => 'Nkamundikum 1',
            'Nkamundikum II' => 'Nkamundikum II',
            'Diffac' => 'Diffac'

            // Add more districts in buea as needed
        ),
        'Kumba II' => array(
            'Puletin' => 'Puletin',
            'Kossalal B' => 'Kossalal B',
            'Utoko' => 'Utoko',
            'Usheme' => 'Usheme',
            'Nshien Nshie' => 'Nshien Nshie',
            'Fiango Ekamba l' => 'Fiango Ekamba l',
            'Kossalai l' => 'Kossalai l',
            'Fiango Ekamba I' => 'Fiango Ekamba I',
            'Kossalal I' => 'Kossalal I',
            'Fiango Ekamba II' => 'Fiango Ekamba II'

            // Add more districts in buea as needed
        ),
        'Kumba III' => array(
            'Cattle Market District' => 'Cattle Market District',
            'Teke' => 'Teke',
            'CCAS District' => 'CCAS District',
            'Dschang Quarter' => 'Dschang Quarter',
            'Barombi Kang' => 'Barombi Kang',
            'Malende' => 'Malende',
            'Mambanda' => 'Mambanda',
            'Mundame' => 'Mundame',
            'Tancha' => 'Tancha',
            'CDC Camps' => 'CDC Camps',
            'Ntam l' => 'Ntam l',
            'Mombo field five' => 'Mombo field five',
            'Ntam II' => 'Ntam II',
            'Ntam III' => 'Ntam III',
            'Mukonje' => 'Mukonje',
            'Fiango Ekueme III' => 'Fiango Ekueme III'

            // Add more districts in buea as needed
        ),
        'Mbonge' => array(
            'Baba' => 'Baba',
            'Bai Bikom' => 'Bai Bikom',
            'Bai Dieka' => 'Bai Dieka',
            'Bai Estate' => 'Bai Estate',
            'Bai Foe' => 'Bai Foe',
            'Bai Grass' => 'Bai Grass',
            'Bai Kuke' => 'Bai Kuke',
            'Bai Longé' => 'Bai Longé',
            'Bai Makemafen' => 'Bai Makemafen',
            'Bai Manya' => 'Bai Manya',
            'Bai Panya' => 'Bai Panya',
            'Bai Sombe' => 'Bai Sombe',
            'Bakumba' => 'Bakumba',
            'Bambuko' => 'Bambuko',
            'Banga Bekele' => 'Banga Bekele',
            'Banga Ngonge' => 'Banga Ngonge',
            'Bangélé' => 'Bangélé',
            'Big Bekondo' => 'Big Bekondo',
            'Big Butu' => 'Big Butu',
            'Big Kotto' => 'Big Kotto',
            'Big Massaka' => 'Big Massaka',
            'Big Nganjo' => 'Big Nganjo',
            'Big Ngbandi' => 'Big Ngbandi',
            'Bikoki' => 'Bikoki',
            'Boa Bakundu' => 'Boa Bakundu',
            'Bokosso' => 'Bokosso',
            'Bole I' => 'Bole I',
            'Bole Bakundu' => 'Bole Bakundu',
            'Bole Dipenda' => 'Bole Dipenda',
            'Bomana Bakweri' => 'Bomana Bakweri',
            'Bombanda' => 'Bombanda',
            'Bombe Bakundu' => 'Bombe Bakundu',
            'Bombele' => 'Bombele',
            'Bonja' => 'Bonja',
            'Bopo' => 'Bopo',
            'Bova' => 'Bova',
            'Boviongo' => 'Boviongo',
            'Dieka Bafaw' => 'Dieka Bafaw',
            'Dienyi' => 'Dienyi',
            'Dissoni' => 'Dissoni',
            'Ebie' => 'Ebie',
            'Ediki' => 'Ediki',
            'Efolofo' => 'Efolofo',
            'Ekombe Bonji' => 'Ekombe Bonji',
            'Ekumbe Ekundunene' => 'Ekumbe Ekundunene',
            'Foé Bakundu' => 'Foé Bakundu',
            'Kombone' => 'Kombone',
            'Kombone Mission' => 'Kombone Mission',
            'Kosse' => 'Kosse',
            'Kotto Barombi' => 'Kotto Barombi',
            'Kotto I' => 'Kotto I',
            'Kotto II' => 'Kotto II',
            'Kuke Kumbo' => 'Kuke Kumbo',
            'Kuke Mbomo' => 'Kuke Mbomo',
            'Kumukumu' => 'Kumukumu',
            'Kwakwa' => 'Kwakwa',
            'Lifenja' => 'Lifenja',
            'Lissombe' => 'Lissombe',
            'Liwenyi' => 'Liwenyi',
            'Lokando I' => 'Lokando I',
            'Lokando II' => 'Lokando II',
            'Mabonji' => 'Mabonji',
            'Mafanja' => 'Mafanja',
            'Marumba Botondoa' => 'Marumba Botondoa',
            'Marumba Bowa' => 'Marumba Bowa',
            'Mbalangi' => 'Mbalangi',
            'Metoko Ma Bekondo' => 'Metoko Ma Bekondo',
            'Mofako Bekondo' => 'Mofako Bekondo',
            'Mofako Butu' => 'Mofako Butu',
            'Mundongo ou Mondongo' => 'Mundongo ou Mondongo',
            'Munyengue Trouble' => 'Munyengue Trouble',
            'Mweli ou Mueli' => 'Mweli ou Mueli',
            'Nake Bokoko' => 'Nake Bokoko',
            'Nake Bongwana' => 'Nake Bongwana',
            'New Barombi' => 'New Barombi',
            'Nganjo' => 'Nganjo',
            'Ngongo' => 'Ngongo',
            'Ngongo Bakundi' => 'Ngongo Bakundi',
            'Njombe' => 'Njombe',
            'Pete Bakundu' => 'Pete Bakundu',
            'Pundu' => 'Pundu',
            'Small Massaka' => 'Small Massaka',
            'Small Ngbandi' => 'Small Ngbandi',
            'Small Nganjo' => 'Small Nganjo',
            'Three Corner Bekondo' => 'Three Corner Bekondo'

            // Add more districts in buea as needed
        ),
        'Mundemba' => array(
            'Akpasang' => 'Akpasang',
            'Bareka' => 'Bareka',
            'Beboka Bima' => 'Beboka Bima',
            'Bekoko' => 'Bekoko',
            'Beoko' => 'Beoko',
            'Bera' => 'Bera',
            'Besingi' => 'Besingi',
            'Boa Bima' => 'Boa Bima',
            'Boa Ngolo' => 'Boa Ngolo',
            'Bulu Camp' => 'Bulu Camp',
            'Ekon I' => 'Ekon I',
            'Ekumbako' => 'Ekumbako',
            'Erat' => 'Erat',
            'Esoki' => 'Esoki',
            'Fabe' => 'Fabe',
            'Ikassa' => 'Ikassa',
            'Ikondo-Kondo I' => 'Ikondo-Kondo I',
            'Isai Mbage Ngolo' => 'Isai Mbage Ngolo',
            'Itoki' => 'Itoki',
            'Ituka' => 'Ituka',
            'Iwa' => 'Iwa',
            'Kuma' => 'Kuma',
            'Lipenja II' => 'Lipenja II',
            'Lipenja Muketi Ngolo' => 'Lipenja Muketi Ngolo',
            'Mabelebele Ngolo' => 'Mabelebele Ngolo',
            'Makeke Camp' => 'Makeke Camp',
            'Mana Camp' => 'Mana Camp',
            'Manja' => 'Manja',
            'Massaka Bima' => 'Massaka Bima',
            'Matamani' => 'Matamani',
            'Meangwe II' => 'Meangwe II',
            'Meka' => 'Meka',
            'Metah' => 'Metah',
            'Mofako' => 'Mofako',
            'Mokange' => 'Mokange',
            'Mokango' => 'Mokango',
            'Mosakoe' => 'Mosakoe',
            'Mosongiselii' => 'Mosongiselii',
            'Ndiba Ngolo' => 'Ndiba Ngolo',
            'Ngenye' => 'Ngenye',
            'Ngumu' => 'Ngumu'

            // Add more districts in buea as needed
        ),
        'Ekondo-Titi' => array(
            'Bafaka' => 'Bafaka',
            'Bekatako' => 'Bekatako',
            'Bisoro' => 'Bisoro',
            'Doh' => 'Doh',
            'Dora' => 'Dora',
            'Ekwe' => 'Ekwe',
            'Gana' => 'Gana',
            'Gogoro' => 'Gogoro',
            'Illor Balondo' => 'Illor Balondo',
            'Ine Usim Kombo' => 'Ine Usim Kombo',
            'Kitta' => 'Kitta',
            'Kotto' => 'Kotto',
            'Kukundu' => 'Kukundu',
            'Kumbe Balondo' => 'Kumbe Balondo',
            'Kumbe Balue' => 'Kumbe Balue',
            'Lipenja' => 'Lipenja',
            'Lobe' => 'Lobe',
            'Makobe' => 'Makobe',
            'Masore' => 'Masore',
            'Metutu' => 'Metutu',
            'Mokono-Barombi' => 'Mokono-Barombi',
            'Nalende' => 'Nalende',
            'Njima' => 'Njima',
            'Nyanga' => 'Nyanga',
            'Pondo Balue' => 'Pondo Balue',
            'Rhumsa' => 'Rhumsa'

            // Add more districts in buea as needed
        ),
        'Bamusso' => array(
            'Baba Ekombe' => 'Baba Ekombe',
            'Barombi Mokoko' => 'Barombi Mokoko',
            'Barombi Ngatame' => 'Barombi Ngatame',
            'Bassenge I' => 'Bassenge I',
            'Bassenge II' => 'Bassenge II',
            'Bassenge III' => 'Bassenge III',
            'Bekarakara' => 'Bekarakara',
            'Bekumu' => 'Bekumu',
            'Betika' => 'Betika',
            'Big Belle' => 'Big Belle',
            'Boa Balondo' => 'Boa Balondo',
            'Boma I Kombo' => 'Boma I Kombo',
            'Boma II Kombo' => 'Boma II Kombo',
            'Bonjale' => 'Bonjale',
            'Dikome' => 'Dikome',
            'Diongo' => 'Diongo',
            'Edikende' => 'Edikende',
            'Ekofarm' => 'Ekofarm',
            'Ekombe Liongo' => 'Ekombe Liongo',
            'Ekombe Mofako' => 'Ekombe Mofako',
            'Ekombe Water Fall' => 'Ekombe Water Fall',
            'Illoani' => 'Illoani',
            'Inefok' => 'Inefok',
            'Jonas Kombo' => 'Jonas Kombo',
            'Kokowaro' => 'Kokowaro',
            'Kombo A Mokoko' => 'Kombo A Mokoko',
            'Likoke-Zion' => 'Likoke-Zion',
            'Mbamba Meme' => 'Mbamba Meme',
            'Mbongo' => 'Mbongo',
            'Meme' => 'Meme',
            'Mokabatanda' => 'Mokabatanda',
            'Mokoko' => 'Mokoko',
            'Monungo' => 'Monungo',
            'New Kesse' => 'New Kesse',
            'Njangassa' => 'Njangassa',
            'Njongi' => 'Njongi',
            'Njongi Camp' => 'Njongi Camp',
            'Three Corners Ekombe' => 'Three Corners Ekombe'

            // Add more districts in buea as needed
        ),
        'Isanguele' => array(
            'Abat' => 'Abat',
            'Ambritip' => 'Ambritip',
            'Ekumamindo' => 'Ekumamindo',
            'Iso\'obo' => 'Iso\'obo',
            'Masaka' => 'Masaka'

            // Add more districts in buea as needed
        ),
        'Idabato' => array(
            'Kombo Amunja I' => 'Kombo Amunja I',
            'Kombo Amunja II' => 'Kombo Amunja II',
            'Kombo Amunja III' => 'Kombo Amunja III'

            // Add more districts in buea as needed
        ),
        'Kombo-Itindi' => array(
            'Efa' => 'Efa',
            'Barracks' => 'Barracks',
            'Black Creek' => 'Black Creek',
            'Bush-Doctor Creek' => 'Bush-Doctor Creek',
            'Eno Creek' => 'Eno Creek',
            'Ete-Ete Creek' => 'Ete-Ete Creek',
            'Eto-Urua' => 'Eto-Urua',
            'Ewondo' => 'Ewondo',
            'Grace Creek' => 'Grace Creek',
            'Imma-Obong Creek' => 'Imma-Obong Creek',
            'Inyang Creek' => 'Inyang Creek',
            'Isu' => 'Isu',
            'Jeremiah Creek' => 'Jeremiah Creek',
            'John Creek' => 'John Creek',
            'Lucky Creek' => 'Lucky Creek',
            'Maculay Creek' => 'Maculay Creek',
            'Maldamia Creek' => 'Maldamia Creek',
            'Ngosso I' => 'Ngosso I',
            'Ngosso II' => 'Ngosso II',
            'Pepsi Creek' => 'Pepsi Creek',
            'Richard And Paul Creek' => 'Richard And Paul Creek',
            'Why Worry Creek' => 'Why Worry Creek'

            // Add more districts in buea as needed
        ),
        'Kombo-Abedimo' => array(
            'Akwa III1' => 'Akwa III1',
            'Akwa IV1' => 'Akwa IV1',
            'Etak-Erat' => 'Etak-Erat',
            'Mission1' => 'Mission1',
            'Ntakaba1' => 'Ntakaba1'

            // Add more districts in buea as needed
        ),
        'Dikome-Balue' => array(
            'Betenge' => 'Betenge',
            'Bona' => 'Bona',
            'Bonji' => 'Bonji',
            'Bosunga' => 'Bosunga',
            'Diboki' => 'Diboki',
            'Dipenda' => 'Dipenda',
            'Ebobe' => 'Ebobe',
            'Itende' => 'Itende',
            'Kombe' => 'Kombe',
            'Mofako Balue' => 'Mofako Balue',
            'Ndonono' => 'Ndonono',
            'Weme' => 'Weme'

            // Add more districts in buea as needed
        ),
        'Toko' => array(
            'Babiabanga' => 'Babiabanga',
            'Banyo' => 'Banyo',
            'Bareka' => 'Bareka',
            'Betika Ngolo' => 'Betika Ngolo',
            'Bokuba' => 'Bokuba',
            'Bombange' => 'Bombange',
            'Burumba' => 'Burumba',
            'Bweme' => 'Bweme',
            'Dibonda' => 'Dibonda',
            'Dienge' => 'Dienge',
            'Dikome Ngolo' => 'Dikome Ngolo',
            'Esukutan' => 'Esukutan',
            'Iboko' => 'Iboko',
            'Ijowe' => 'Ijowe',
            'Ikenge' => 'Ikenge',
            'Ikoi' => 'Ikoi',
            'Ikoti' => 'Ikoti',
            'Ilondo' => 'Ilondo',
            'Ipongi' => 'Ipongi',
            'Itali' => 'Itali',
            'Iwasa' => 'Iwasa',
            'Iyombo' => 'Iyombo',
            'Kilikile' => 'Kilikile',
            'Lipenja I' => 'Lipenja I',
            'Lobe' => 'Lobe',
            'Madie I' => 'Madie I',
            'Manya' => 'Manya',
            'Massaka' => 'Massaka',
            'Mayeka' => 'Mayeka',
            'Mobenge' => 'Mobenge',
            'Moboka' => 'Moboka',
            'Mofako' => 'Mofako',
            'Ndoi' => 'Ndoi',
            'Ngamoki' => 'Ngamoki',
            'Tombe' => 'Tombe'
            // Add more districts in buea VI as needed
        ),
        'Bamenda I' => array(
            'Abangoh Central' => 'Abangoh Central',
            'Abangoh Ntahsa (Nkwen)' => 'Abangoh Ntahsa (Nkwen)',
            'Abangoh Ngang' => 'Abangoh Ngang',
            'Achichum' => 'Achichum',
            'Alahnting' => 'Alahnting',
            'Aningdoh' => 'Aningdoh',
            'Ayaba' => 'Ayaba',
            'Nta\'Afi' => 'Nta\'Afi',
            'Ntanche' => 'Ntanche'

            // Add more districts in Douala I as needed
        ),
        'Bali' => array(
            'Bawock' => 'Bawock',
            'Beisen' => 'Beisen',
            'Bossa' => 'Bossa',
            'Gungong' => 'Gungong',
            'Koppin' => 'Koppin',
            'Kutadnchi' => 'Kutadnchi',
            'Mantum' => 'Mantum',
            'Mbatmandet' => 'Mbatmandet',
            'Mbeluh' => 'Mbeluh',
            'Mbufung' => 'Mbufung',
            'Naka' => 'Naka',
            'Mudum' => 'Mudum',
            'Wossing' => 'Wossing'

            // Add more districts in Douala II as needed
        ),
        'Tubah' => array(
            'Atogam' => 'Atogam',
            'Baforkum' => 'Baforkum',
            'Bambili' => 'Bambili',
            'Bambui' => 'Bambui',
            'Djakala' => 'Djakala',
            'Finge' => 'Finge',
            'Kedjom Keku' => 'Kedjom Keku',
            'Kedjom Ketinguh' => 'Kedjom Ketinguh',
            'Mobwefoumanju' => 'Mobwefoumanju',
            'Nduomilele' => 'Nduomilele',
            'Sabga' => 'Sabga'

            // Add more districts in Douala III as needed
        ),
        'Bafut' => array(
            'Agyati' => 'Agyati',
            'Bujong' => 'Bujong',
            'Manji' => 'Manji',
            'Mankaha' => 'Mankaha',
            'Mbebali' => 'Mbebali',
            'Nchum' => 'Nchum',
            'Niko' => 'Niko',
            'Njibujang' => 'Njibujang',
            'Njinteh' => 'Njinteh',
            'Nsem' => 'Nsem',
            'Akosia-Mforya' => 'Akosia-Mforya',
            'Bawum' => 'Bawum',
            'Bukari' => 'Bukari',
            'Butang' => 'Butang',
            'Buwe-Acheni' => 'Buwe-Acheni',
            'Buwi' => 'Buwi',
            'Mambu' => 'Mambu',
            'Mankanikong' => 'Mankanikong',
            'Mankwi' => 'Mankwi',
            'Mantaa' => 'Mantaa',
            'Mbakong' => 'Mbakong',
            'Mbebili' => 'Mbebili',
            'Mundum' => 'Mundum',
            'Nsoh' => 'Nsoh',
            'Ntabuwe' => 'Ntabuwe',
            'Ntangoh' => 'Ntangoh'

            // Add more districts in Douala IV as needed
        ),
        'Santa' => array(

            // Add more districts in Douala V as needed
        ),
        'Bamenda II' => array(
            'Alakuma' => 'Alakuma',
            'Atuakom' => 'Atuakom',
            'Atu-Azire (Meta Quarter, Big Mankon)' => 'Atu-Azire (Meta Quarter, Big Mankon)',
            'Azire (Small Mankon)' => 'Azire (Small Mankon)',
            'Chindeh' => 'Chindeh',
            'Lower Ngomgham' => 'Lower Ngomgham',
            'Mbingfibiel' => 'Mbingfibiel',
            'Musang' => 'Musang',
            'Nitob I' => 'Nitob I',
            'Nitob II' => 'Nitob II',
            'Nitob III' => 'Nitob III',
            'Nitob IV' => 'Nitob IV',
            'Ntambeng I (Old Town)' => 'Ntambeng I (Old Town)',
            'Ntambeng II (Old Town)' => 'Ntambeng II (Old Town)',
            'Ntamulung' => 'Ntamulung',
            'Ntarikon' => 'Ntarikon',
            'Ntatru' => 'Ntatru',
            'Upper Ngomgham' => 'Upper Ngomgham',
            'Muwatsu' => 'Muwatsu',
            'Nkvura' => 'Nkvura',
            'Mulang' => 'Mulang',
            'Akumlam' => 'Akumlam',
            'Alabukom' => 'Alabukom',
            'Alachu' => 'Alachu',
            'Alafrumbi' => 'Alafrumbi',
            'Alamandom' => 'Alamandom',
            'Alamatu' => 'Alamatu',
            'Alatah' => 'Alatah',
            'Alatakoh' => 'Alatakoh',
            'Asongkah' => 'Asongkah',
            'Atua Mambu' => 'Atua Mambu',
            'Atuafon' => 'Atuafon',
            'Atualakom' => 'Atualakom',
            'Bagbanong' => 'Bagbanong',
            'Bagmande' => 'Bagmande',
            'Kukvung' => 'Kukvung',
            'Maso' => 'Maso',
            'Matsam' => 'Matsam',
            'Matsom' => 'Matsom',
            'Ndzong' => 'Ndzong',
            'Ndzumabuah' => 'Ndzumabuah',
            'Ngulung' => 'Ngulung',
            'Ntakimbari' => 'Ntakimbari',
            'Ntamafe' => 'Ntamafe',
            'Ntamambu' => 'Ntamambu',
            'Ntambeng' => 'Ntambeng',
            'Ntangien' => 'Ntangien',
            'Ntankah' => 'Ntankah',
            'Ntumbong' => 'Ntumbong',
            'Mbatu Ntaw' => 'Mbatu Ntaw',
            'Nsongwa' => 'Nsongwa',
            'Nkingkak' => 'Nkingkak',
            'Chomba' => 'Chomba'

            // Add more districts in Douala V as needed
        ),
        'Bamenda III' => array(
            'Bayelle I' => 'Bayelle I',
            'Bayelle II' => 'Bayelle II',
            'Bayelle III' => 'Bayelle III',
            'Mugheb' => 'Mugheb',
            'Nkwasi' => 'Nkwasi',
            'Ntaghem' => 'Ntaghem',
            'Ntahbru' => 'Ntahbru',
            'Ntakikah' => 'Ntakikah',
            'Ntenefor' => 'Ntenefor',
            'Sisia I' => 'Sisia I',
            'Sisia II' => 'Sisia II',
            'Bayelle IIA' => 'Bayelle IIA',
            'Ntenefor Nkwen' => 'Ntenefor Nkwen',
            'Ndzah' => 'Ndzah',
            'Nkwen' => 'Nkwen',
            'Alalie' => 'Alalie',
            'Atiela' => 'Atiela',
            'Atienta' => 'Atienta',
            'Bayelle Manda' => 'Bayelle Manda',
            'Bujong' => 'Bujong',
            'Futru I' => 'Futru I',
            'Futru II' => 'Futru II',
            'Manka' => 'Manka',
            'Mante-Ntente' => 'Mante-Ntente',
            'Mbefi' => 'Mbefi',
            'Mbelem' => 'Mbelem',
            'Mbesoh' => 'Mbesoh',
            'Mbung' => 'Mbung',
            'Menjung' => 'Menjung',
            'Mubang' => 'Mubang',
            'Munka' => 'Munka',
            'Nchang' => 'Nchang',
            'Njenefor' => 'Njenefor',
            'Nketesoh' => 'Nketesoh',
            'Nkwenjang' => 'Nkwenjang',
            'Ntasen' => 'Ntasen',
            'Ntefinki' => 'Ntefinki',
            'Ntilla' => 'Ntilla',
            'Tubah' => 'Tubah',
            'Ntatubuh' => 'Ntatubuh',
            'Ntahkekah' => 'Ntahkekah'

            // Add more districts in Douala VI as needed
        ),
    );

    foreach ($states_cameroon as $district => $cities) {
        foreach ($cities as $city => $cityValue) {
            $map[$city] = $cityValue . ', ' . $district;
        }
    }

    $states['CM'] = array(
        'Yaoundé I' => 'Yaoundé I',
        'Yaoundé II' => 'Yaoundé II',
        'Yaoundé III' => 'Yaoundé III',
        'Yaoundé IV' => 'Yaoundé IV',
        'Yaoundé V' => 'Yaoundé V',
        'Yaoundé VI' => 'Yaoundé VI',
        'Yaoundé VII' => 'Yaoundé VII',
        // Add districts from littoral to littoral
        'Douala I' => 'Douala I',
        'Douala II' => 'Douala II',
        'Douala III' => 'Douala III',
        'Douala IV' => 'Douala IV',
        'Douala V' => 'Douala V',
        'Douala VI' => 'Douala VI',
        // Add districts from southwest to southwest
        'Bangem' => 'Bangem',
        'Nguti' => 'Nguti',
        'Tombel' => 'Tombel',
        'Alou' => 'Alou',
        'Menji' => 'Menji',
        'Akwaya' => 'Akwaya',
        'Eyumodjock' => 'Eyumodjock',
        'Central Mamfé' => 'Central Mamfé',
        'Upper Bayang' => 'Upper Bayang',
        'Konye' => 'Konye',
        'Kumba I' => 'Kumba I',
        'Kumba II' => 'Kumba II',
        'Kumba III' => 'Kumba III',
        'Mbonge' => 'Mbonge',
        'Mundemba' => 'Mundemba',
        'Ekondo-Titi' => 'Ekondo-Titi',
        'Bamusso' => 'Bamusso',
        'Isanguele' => 'Isanguele',
        'Idabato' => 'Idabato',
        'Kombo-Itindi' => 'Kombo-Itindi',
        'Kombo-Abedimo' => 'Kombo-Abedimo',
        'Dikome-Balue' => 'Dikome-Balue',
        'Toko' => 'Toko',
        // Add districts from northwest to northwest
        'Bamenda I' => 'Bamenda I',
        'Bali' => 'Bali',
        'Tubah' => 'Tubah',
        'Bafut' => 'Bafut',
        'Santa' => 'Santa',
        'Bamenda II' => 'Bamenda II',
        'Bamenda III' => 'Bamenda III',
    );

    $states['CM'] = $map;

    return $states;
}
?>