#!/bin/bash
# test-video-mobile.sh
# Manual test for mobile video playback
# Run: bash scripts/test-video-mobile.sh

echo ""
echo "🎬 === Video Playback Test Instructions ==="
echo ""
echo "To test if video playback is working on mobile:"
echo ""
echo "1. Upload a video status:"
echo "   • Go to your mobile browser"
echo "   • Open the app and navigate to Status Creator"
echo "   • Select a video file (30-60 seconds recommended)"
echo "   • Upload it"
echo ""
echo "2. View the status:"
echo "   • Go to Discovery Hub → Status Tab"
echo "   • Tap the video you just uploaded"
echo ""
echo "3. Check for these signs of success:"
echo "   ✅ Video loads within 2-3 seconds (not 30+ seconds)"
echo "   ✅ Playback is smooth (no constant buffering)"
echo "   ✅ Can scrub/seek through the video"
echo "   ✅ Audio plays (if included in original video)"
echo "   ✅ Works on 3G/4G networks (not just WiFi)"
echo ""
echo "4. If it works:"
echo "   • Video compression is active (file ~2-5MB)"
echo "   • S3 streaming headers are being used"
echo "   • Mobile playback is optimized"
echo ""
echo "5. If it still has issues:"
echo "   • Check backend logs: npm run logs"
echo "   • Look for: '[Video] Compressing...' messages"
echo "   • Verify FFmpeg: ffmpeg -version"
echo ""
echo "═════════════════════════════════════════════"
echo ""
