#!/usr/bin/env node

/**
 * setup-env.js
 * Creates or refreshes .env.local with the backend API host.
 *
 * Usage:
 *   node setup-env.js
 *   node setup-env.js 13.61.104.192
 *   AURA_API_HOST=13.61.104.192 node setup-env.js
 */

import fs from 'fs';
import path from 'path';
import os from 'os';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const getLocalIP = () => {
  const interfaces = os.networkInterfaces();
  for (const addrs of Object.values(interfaces)) {
    for (const addr of addrs) {
      if (addr.family === 'IPv4' && !addr.internal) {
        return addr.address;
      }
    }
  }
  return 'localhost';
};

const getTargetHost = () => process.argv[2] || process.env.AURA_API_HOST || getLocalIP();

const createEnvLocal = () => {
  const apiHost = getTargetHost();
  const envPath = path.join(__dirname, '.env.local');
  const content = `# Auto-generated by setup-env.js on ${new Date().toISOString()}
# API host: ${apiHost}
# If this IP changes, re-run: node setup-env.js <new-ip-or-hostname>

NEXT_PUBLIC_API_URL=http://${apiHost}:5000/api/v1
NEXT_PUBLIC_SOCKET_URL=http://${apiHost}:5000
`;

  fs.writeFileSync(envPath, content, 'utf8');
  console.log('Updated .env.local');
  console.log(`API URL: http://${apiHost}:5000/api/v1`);
  console.log(`Socket URL: http://${apiHost}:5000`);
  console.log(`Frontend: http://${apiHost}:3000`);
  console.log(`File location: ${envPath}`);
  console.log('\nReady! Run: npm run dev:network');
};

try {
  createEnvLocal();
} catch (err) {
  console.error('Error creating .env.local:', err.message);
  process.exit(1);
}
