#!/usr/bin/env node

/**
 * setup-env.js
 * Automatically creates .env.local with your local IP address
 * Run this once: node setup-env.js
 */

import fs from 'fs';
import path from 'path';
import os from 'os';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Get local IP address
const getLocalIP = () => {
  const interfaces = os.networkInterfaces();
  for (const [name, addrs] of Object.entries(interfaces)) {
    for (const addr of addrs) {
      if (addr.family === 'IPv4' && !addr.internal) {
        return addr.address;
      }
    }
  }
  return 'localhost';
};

// Create .env.local
const createEnvLocal = () => {
  const localIP = getLocalIP();
  const envPath = path.join(__dirname, '.env.local');
  
  // Check if .env.local already exists
  if (fs.existsSync(envPath)) {
    console.log('✅ .env.local already exists');
    console.log(`📍 Content: http://${localIP}:5000/api/v1`);
    return;
  }
  
  const content = `# Auto-generated by setup-env.js on ${new Date().toISOString()}
# Your local IP: ${localIP}
# If this IP changes, re-run: node setup-env.js

NEXT_PUBLIC_API_URL=http://${localIP}:5000/api/v1
`;
  
  fs.writeFileSync(envPath, content, 'utf8');
  console.log('✅ Created .env.local');
  console.log(`📍 API URL: http://${localIP}:5000/api/v1`);
  console.log(`📍 Frontend: http://${localIP}:3000`);
  console.log(`📝 File location: ${envPath}`);
  console.log('\n🚀 Ready! Run: npm run dev:network');
};

try {
  createEnvLocal();
} catch (err) {
  console.error('❌ Error creating .env.local:', err.message);
  process.exit(1);
}
