"use client";

import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { useAuthStore } from '@/hooks/useAuth';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'fr', label: 'French', nativeLabel: 'Francais' },
];

const STORAGE_KEY = 'aura_language';

const labelSlug = (value = '') =>
  String(value)
    .trim()
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '.')
    .replace(/^\.+|\.+$/g, '');

const SYSTEM_TRANSLATIONS = {
  en: {
    'common.all': 'All',
    'common.market': 'Market',
    'common.back': 'Back',
    'common.selected': 'Selected',
    'common.loadingCategories': 'Loading categories...',
    'common.noSubcategories': 'No subcategories - "{value}" selected',
    'common.follow': 'Follow',
    'common.following': 'Following',
    'common.chat': 'Chat',
    'common.contact': 'Contact',
    'common.buyNow': 'Buy now',
    'common.outOfStock': 'Out of stock',
    'common.addedToCart': '{name} added to cart',
    'common.loginCart': 'Please login to activate cart',
    'common.loginProceed': 'Please login to proceed',
    'common.loginWishlist': 'Please login to wishlist',
    'common.loginChat': 'Please login to chat',
    'common.wishlistFailed': 'Failed to update wishlist',
    'common.verifiedVendor': 'Verified vendor',
    'common.verifiedStore': 'Verified Store',
    'common.globalMarket': 'Global Market',
    'common.results': 'Results',
    'common.price': 'Price',
    'common.anyPrice': 'Any Price',
    'common.sort': 'Sort',
    'common.shopSyncing': 'Shop syncing',
    'common.noProductsFound': 'No Products Found',
    'common.productsArrive': 'Products appear here as soon as the latest shop feed arrives.',
    'common.noMatches': 'No matches found for your current search or filters.',
    'common.resetFilters': 'Reset Filters',
    'common.network': 'Network',
    'common.walletBalance': 'Wallet balance',
    'common.store': 'Store',
    'common.verifiedNode': 'Verified node',
    'common.refresh': 'Refresh',
    'common.cancel': 'Cancel',
    'common.active': 'Active',
    'common.hidden': 'Hidden',
    'common.user': 'User',
    'common.role': 'Role',
    'common.status': 'Status',
    'common.amount': 'Amount',
    'common.actions': 'Actions',
    'common.unknown': 'Unknown',
    'common.activate': 'Activate',
    'common.refund': 'Refund',
    'common.hide': 'Hide',
    'common.show': 'Show',
    'nav.signals': 'Signals',
    'nav.accountConfiguration': 'Account Configuration',
    'nav.marketplace': 'Marketplace',
    'nav.dashboard': 'Dashboard',
    'nav.subscription': 'Subscription',
    'nav.products': 'Products',
    'nav.aura.stories': 'Aura Stories',
    'nav.orders': 'Orders',
    'nav.client.ratings': 'Client Ratings',
    'nav.disputes': 'Disputes',
    'nav.messages': 'Messages',
    'nav.wallet': 'Wallet',
    'nav.analytics': 'Analytics',
    'nav.users': 'Users',
    'nav.vendors': 'Vendors',
    'nav.system.comms': 'System Comms',
    'nav.vendor.kyc': 'Vendor KYC',
    'nav.escrow.and.fees': 'Escrow & Fees',
    'nav.withdrawals': 'Withdrawals',
    'nav.transactions': 'Transactions',
    'nav.subscriptions': 'Subscriptions',
    'nav.shipment.node': 'Shipment Node',
    'nav.logistics.earnings': 'Logistics Earnings',
    'nav.categories': 'Categories',
    'nav.reviews': 'Reviews',
    'nav.email.logs': 'Email Logs',
    'nav.audit.ledger': 'Audit Ledger',
    'nav.cms.hero': 'CMS / Hero',
    'nav.wishlist': 'Wishlist',
    'nav.profile': 'Profile',
    'nav.security': 'Security',
    'nav.network': 'Network',
    'nav.verification': 'Verification',
    'nav.alerts': 'Alerts',
    'nav.manifests': 'Manifests',
    'nav.route.pricing': 'Route Pricing',
    'nav.live.tracking': 'Live Tracking',
    'nav.relay.nodes': 'Relay Nodes',
    'roleSidebar.customer.label': 'Aura Member',
    'roleSidebar.vendor.label': 'Vendor Premium',
    'roleSidebar.admin.label': 'Governance Mode',
    'roleSidebar.logistics.label': 'Fulfillment Node',
    'subscription.access': 'access',
    'subscription.storeActive': 'Store active',
    'subscription.packageActive': 'Package active',
    'subscription.graceShort': 'Grace active',
    'subscription.packageNeeded': 'Package needed',
    'subscription.viewPackages': 'View packages',
    'subscription.vendorGraceInline': 'Your vendor tools are available during grace. Activate a package to keep selling without interruption.',
    'subscription.vendorLimitedInline': 'You can view your dashboard, but selling actions need an active package.',
    'subscription.mostPopular': 'Most popular',
    'subscription.talkToUs': 'Talk to us',
    'subscription.contactUs': 'Contact us',
    'subscription.getStarted': 'Get started',
    'subscription.contactDetail': 'This package is handled directly by support so the offer can match your operation.',
    'subscription.powerSellerHelp': 'Talk to Auradime support for custom pricing, homepage placement, API access, and account management.',
    'subscription.durationDays': 'Duration days',
    'subscription.contactOnly': 'Contact-only package',
    'subscription.days': 'days',
    'subscription.hidePlan': 'Hide package',
    'subscription.activatePlan': 'Activate package',
    'subscription.noticeWarning': 'Action needed',
    'subscription.noticeCritical': 'Restricted',
    'subscription.title': 'Activate your workspace',
    'subscription.description': 'This role requires an active package before dashboard tools can be used. Your subscription is checked securely on the server.',
    'subscription.activeToast': 'Subscription active.',
    'subscription.loadFailed': 'Could not load subscription.',
    'subscription.phoneRequired': 'Phone number is required.',
    'subscription.activated': 'Subscription activated.',
    'subscription.requestSent': 'Payment request sent.',
    'subscription.paymentFailed': 'Subscription payment failed.',
    'subscription.alreadyActive': 'Your subscription is active',
    'subscription.alreadyActiveDetail': 'You can continue to your dashboard and use your role features.',
    'subscription.continueDashboard': 'Continue',
    'subscription.payTitle': 'Payment',
    'subscription.payDetail': 'Choose the method that is easiest for you.',
    'subscription.wallet': 'Aura Wallet',
    'subscription.mobileMoney': 'Mobile money / card',
    'subscription.collectionFee': 'Collection fee is added only for external collection.',
    'subscription.phone': 'Phone number',
    'subscription.secureCheck': 'Access is checked server-side on every gated request.',
    'subscription.activateButton': 'Activate package',
    'subscription.adminTitle': 'Subscription Control',
    'subscription.adminSubtitle': 'Manage role gates, packages, subscribers, and subscription revenue.',
    'subscription.adminLoadFailed': 'Could not load subscriptions.',
    'subscription.requirementsSaved': 'Subscription requirements saved.',
    'subscription.saveFailed': 'Could not save changes.',
    'subscription.planNameRequired': 'Plan name is required.',
    'subscription.planSaved': 'Plan saved.',
    'subscription.subscriptionUpdated': 'Subscription updated.',
    'subscription.activeSubscribers': 'Active subscribers',
    'subscription.revenue': 'Subscription revenue',
    'subscription.pending': 'Pending payments',
    'subscription.activePlans': 'Active plans',
    'subscription.graceUsers': 'Grace users',
    'subscription.limitedUsers': 'Limited users',
    'subscription.graceDays': 'Grace days',
    'subscription.graceTitle': 'Subscription grace active',
    'subscription.graceDetail': 'You can keep using your workspace during this grace period. Activate a package before it ends to keep full access.',
    'subscription.limitedTitle': 'Limited access mode',
    'subscription.limitedDetail': 'You can still view your dashboard, but subscription-gated actions are paused until you activate a package.',
    'subscription.subscribeCta': 'Subscribe',
    'subscription.startDate': 'Start date',
    'subscription.expiryDate': 'Expiry date',
    'subscription.roleRequirements': 'Role requirements',
    'subscription.roleRequirementsDetail': 'Admin is never gated. Toggle only roles that should pay before using role tools.',
    'subscription.editPlan': 'Edit plan',
    'subscription.newPlan': 'New plan',
    'subscription.planName': 'Plan name',
    'subscription.descriptionField': 'Description',
    'subscription.oneTime': 'One-time',
    'subscription.monthly': 'Monthly',
    'subscription.yearly': 'Yearly',
    'subscription.featuresHelp': 'One feature per line',
    'subscription.savePlan': 'Save plan',
    'subscription.plans': 'Plans',
    'subscription.subscribers': 'Subscribers',
    'subscription.subscribersDetail': 'Recent subscription history and payment status.',
    'subscription.plan': 'Plan',
    'subscription.noSubscribers': 'No subscribers yet.',
    'subscription.manualRequired': 'User ID and plan are required.',
    'subscription.manualActivation': 'Manual activation',
    'subscription.manualActivationDetail': 'Activate a package for a user by ID when support confirms payment or grants access.',
    'subscription.userId': 'User ID',
    'subscription.choosePlan': 'Choose plan',
    'subscription.activateUser': 'Activate user',
    'wallet.availableBalance': 'Available Balance',
    'wallet.secureAccount': 'Secure Account',
    'wallet.available': 'Available',
    'wallet.availableToSpend': 'Available to spend',
    'wallet.inEscrow': 'In escrow',
    'wallet.heldInEscrow': 'Held in escrow',
    'wallet.successful': 'Successful',
    'wallet.failed': 'Failed',
    'wallet.paymentsDeclined': 'Payments declined',
    'wallet.depositMoney': 'Deposit Money',
    'wallet.withdrawMoney': 'Withdraw Money',
    'wallet.transactionHistory': 'Transaction History',
    'wallet.realTimeHistory': 'Real-time transaction history',
    'wallet.noRecords': 'No {type} records found',
    'wallet.withdrawal': 'withdrawal',
    'wallet.checking': 'Checking...',
    'wallet.recheckPayment': 'Recheck payment',
    'wallet.tab.all': 'all',
    'wallet.tab.in': 'in',
    'wallet.tab.out': 'out',
    'wallet.tab.withdrawals': 'withdrawals',
    'overtime.shopByCategory': 'Shop by Category',
    'overtime.browse': 'Browse',
    'overtime.explore': 'Explore',
    'overtime.exploreCollection': 'Explore Collection',
    'overtime.topRatedVendors': 'Top Rated Vendors',
    'overtime.vendorFallback': 'Discover premium products from this trusted seller.',
    'shop.exploreStores': 'Explore Stores',
    'shop.globalDiscovery': 'Global Discovery',
    'product.notFound': 'Product not found',
    'product.backToShop': 'Back to Shop',
    'product.home': 'Home',
    'product.shop': 'Shop',
    'product.addedWishlist': 'Added to wishlist',
    'product.removedWishlist': 'Removed from wishlist',
    'product.linkCopied': 'Link copied!',
    'product.cartFailed': 'Cart update failed',
    'product.addToCart': 'Add to cart',
    'product.unableSeller': 'Unable to reach seller.',
    'product.verified': 'Aura market verified',
    'product.new': 'New',
    'product.available': '{count} available',
    'product.selectOption': 'Select {name}',
    'product.description': 'Description',
    'product.reviews': 'Reviews',
    'product.seeAll': 'See all',
    'product.noReviews': 'No reviews yet.',
    'product.buyer': 'Buyer',
    'product.verifiedPurchase': 'Verified purchase',
    'product.quantity': 'Quantity',
    'product.yourItem': 'Your listed item',
    'product.currentlyOut': 'Currently out of stock',
    'product.deliveryReturns': 'Delivery & returns',
    'product.expressDelivery': 'Express delivery',
    'product.deliveryWindow': '24-48h in major cities',
    'product.freeReturns': 'Free returns',
    'product.returnPolicy': '7-day easy return policy',
    'product.soldBy': 'Sold by',
    'product.rating': 'Rating',
    'product.visitStore': 'Visit store',
    'product.details': 'Details',
    'product.specifications': 'Specifications',
    'product.category': 'Category',
    'product.brand': 'Brand',
    'product.condition': 'Condition',
    'product.sku': 'SKU',
    'product.seller': 'Seller',
    'product.general': 'General',
    'product.brandNew': 'Brand new',
    'product.unitsAvailable': '{count} units available',
    'product.officialStore': 'Official store',
    'product.related': 'You may also like',
    'product.viewAll': 'View all',
    'search.productsPlaceholder': 'Search premium products...',
    'search.ordersPlaceholder': 'Search by order ID or product',
    'role.customer': 'customer',
    'role.vendor': 'vendor',
    'role.logistics': 'logistics',
    'orders.title': 'Orders',
    'orders.vendorHelp': 'Track purchases you made and sales from your store.',
    'orders.customerHelp': 'View and track your order history.',
    'orders.refresh': 'Refresh',
    'orders.myPurchases': 'My purchases',
    'orders.mySales': 'My sales',
    'orders.total': 'Total',
    'orders.active': 'Active',
    'orders.completed': 'Completed',
    'orders.issues': 'Issues',
    'orders.history': 'Order history',
    'orders.shown': '{count} shown',
    'orders.loading': 'Loading orders...',
    'orders.none': 'No orders found.',
    'orders.item': 'item',
    'orders.items': 'items',
    'status.all': 'All',
    'status.placed': 'Placed',
    'status.processing': 'Processing',
    'status.shipped': 'Shipped',
    'status.completed': 'Completed',
    'status.failed': 'Failed',
    'status.cancelled': 'Cancelled',
    'status.refunded': 'Refunded',
    'status.delivered': 'Delivered',
    'status.pending': 'Pending',
    'status.refundedToWallet': 'Refunded to wallet',
    'status.refundPending': 'Refund pending',
    'status.walletCredited': 'Wallet credited',
    'status.payOnDelivery': 'Pay on delivery',
    'status.paid': 'Paid',
    'status.inStock': 'In stock',
    'sort.newest': 'Newest Arrivals',
    'sort.priceLowHigh': 'Price: Low to High',
    'sort.priceHighLow': 'Price: High to Low',
    'sort.highestRated': 'Highest Rated',
    'price.under5000': 'Under 5,000 XAF',
    'price.5000to10000': '5,000 - 10,000 XAF',
    'price.10000to50000': '10,000 - 50,000 XAF',
    'price.over50000': 'Over 50,000 XAF',
    'label.electronics': 'Electronics',
    'label.mens.clothing': 'Mens Clothing',
    'label.health.and.fitness': 'Health & Fitness',
    'label.laptops': 'Laptops',
    'label.smartwatches': 'Smartwatches',
    'label.shoulder.bags': 'Shoulder Bags',
    'label.hoodies': 'Hoodies',
    'label.charcoal.grills': 'Charcoal Grills',
    'label.keyboards.and.mice': 'Keyboards & Mice',
    'label.books': 'Books',
    'label.printed.books': 'Printed Books',
    'label.fiction': 'Fiction',
    'label.non.fiction': 'Non-Fiction',
    'label.childrens.books': "Children's Books",
    'label.graphic.novels': 'Graphic Novels',
    'label.poetry': 'Poetry',
    'label.home.and.kitchen': 'Home & Kitchen',
    'label.fashion.and.lifestyle': 'Fashion & Lifestyle',
    'label.beauty.and.personal.care': 'Beauty & Personal Care',
    'label.kids.and.baby.clothing': 'Kids & Baby Clothing',
    'label.sports.and.outdoors': 'Sports & Outdoors',
    'label.flash.sale': 'Flash Sale',
    'label.new.arrival': 'New Arrival',
    'label.available.for.delivery': 'Available for Delivery',
    'label.looking.for': 'Looking For',
    'label.store.update': 'Store Update',
    'label.moment': 'Moment',
    'label.review.and.recommend': 'Review & Recommend',
    'label.trade.swap': 'Trade / Swap',
    'label.service.offer': 'Service Offer',
    'label.order.update': 'Order Update',
    'label.alert': 'Alert',
    'label.community': 'Community',
    'label.best.sellers': 'Best Sellers',
    'label.top.rated.vendors': 'Top Rated Vendors',
    'label.featured.products': 'Featured Products',
    'label.featured': 'Featured',
    'label.hype.drop.energy': 'Hype Drop Energy',
    'label.the.drop.you.ve.been.waiting.for.auradime.is.live': "The Drop You've Been Waiting For - AuraDime Is Live.",
    'label.your.aura.found.its.match.auradime.is.here': 'Your Aura Found Its Match. AuraDime Is Here.',
    'label.community.vibe': 'Community Vibe',
    'label.explore.collection': 'Explore Collection',
  },
  fr: {
    'common.all': 'Tout',
    'common.market': 'Marche',
    'common.back': 'Retour',
    'common.selected': 'Selectionne',
    'common.loadingCategories': 'Chargement des categories...',
    'common.noSubcategories': 'Aucune sous-categorie - "{value}" selectionne',
    'common.follow': 'Suivre',
    'common.following': 'Suivi',
    'common.chat': 'Discussion',
    'common.contact': 'Contacter',
    'common.buyNow': 'Acheter',
    'common.outOfStock': 'Rupture',
    'common.addedToCart': '{name} ajoute au panier',
    'common.loginCart': 'Connectez-vous pour utiliser le panier',
    'common.loginProceed': 'Connectez-vous pour continuer',
    'common.loginWishlist': 'Connectez-vous pour ajouter aux favoris',
    'common.loginChat': 'Connectez-vous pour discuter',
    'common.wishlistFailed': 'Impossible de mettre a jour les favoris',
    'common.verifiedVendor': 'Vendeur verifie',
    'common.verifiedStore': 'Boutique verifiee',
    'common.globalMarket': 'Marche global',
    'common.results': 'Resultats',
    'common.price': 'Prix',
    'common.anyPrice': 'Tous les prix',
    'common.sort': 'Trier',
    'common.shopSyncing': 'Synchronisation',
    'common.noProductsFound': 'Aucun produit trouve',
    'common.productsArrive': 'Les produits apparaissent ici des que la boutique se synchronise.',
    'common.noMatches': 'Aucun resultat pour votre recherche ou vos filtres.',
    'common.resetFilters': 'Reinitialiser',
    'common.network': 'Reseau',
    'common.walletBalance': 'Solde wallet',
    'common.store': 'Boutique',
    'common.verifiedNode': 'Boutique verifiee',
    'common.refresh': 'Actualiser',
    'common.cancel': 'Annuler',
    'common.active': 'Actif',
    'common.hidden': 'Masque',
    'common.user': 'Utilisateur',
    'common.role': 'Role',
    'common.status': 'Statut',
    'common.amount': 'Montant',
    'common.actions': 'Actions',
    'common.unknown': 'Inconnu',
    'common.activate': 'Activer',
    'common.refund': 'Rembourser',
    'common.hide': 'Masquer',
    'common.show': 'Afficher',
    'nav.signals': 'Signaux',
    'nav.accountConfiguration': 'Configuration du compte',
    'nav.marketplace': 'Marche',
    'nav.dashboard': 'Tableau de bord',
    'nav.subscription': 'Abonnement',
    'nav.products': 'Produits',
    'nav.aura.stories': 'Stories',
    'nav.orders': 'Commandes',
    'nav.client.ratings': 'Notes clients',
    'nav.disputes': 'Litiges',
    'nav.messages': 'Messages',
    'nav.wallet': 'Wallet',
    'nav.analytics': 'Analyses',
    'nav.users': 'Utilisateurs',
    'nav.vendors': 'Vendeurs',
    'nav.system.comms': 'Messages systeme',
    'nav.vendor.kyc': 'KYC vendeur',
    'nav.escrow.and.fees': 'Fonds bloques et frais',
    'nav.withdrawals': 'Retraits',
    'nav.transactions': 'Transactions',
    'nav.subscriptions': 'Abonnements',
    'nav.shipment.node': 'Expeditions',
    'nav.logistics.earnings': 'Revenus logistiques',
    'nav.categories': 'Categories',
    'nav.reviews': 'Avis',
    'nav.email.logs': 'Emails',
    'nav.audit.ledger': 'Journal audit',
    'nav.cms.hero': 'CMS / Hero',
    'nav.wishlist': 'Favoris',
    'nav.profile': 'Profil',
    'nav.security': 'Securite',
    'nav.network': 'Reseau',
    'nav.verification': 'Verification',
    'nav.alerts': 'Alertes',
    'nav.manifests': 'Manifestes',
    'nav.route.pricing': 'Prix des routes',
    'nav.live.tracking': 'Suivi live',
    'nav.relay.nodes': 'Noeuds relais',
    'roleSidebar.customer.label': 'Membre Aura',
    'roleSidebar.vendor.label': 'Vendeur Premium',
    'roleSidebar.admin.label': 'Mode gouvernance',
    'roleSidebar.logistics.label': 'Noeud logistique',
    'subscription.access': 'acces',
    'subscription.storeActive': 'Boutique active',
    'subscription.packageActive': 'Package actif',
    'subscription.graceShort': 'Grace active',
    'subscription.packageNeeded': 'Package requis',
    'subscription.viewPackages': 'Voir les packages',
    'subscription.vendorGraceInline': 'Vos outils vendeur restent disponibles pendant la grace. Activez un package pour continuer a vendre sans interruption.',
    'subscription.vendorLimitedInline': 'Vous pouvez consulter votre tableau de bord, mais les actions de vente exigent un package actif.',
    'subscription.mostPopular': 'Le plus choisi',
    'subscription.talkToUs': 'Parlez-nous',
    'subscription.contactUs': 'Nous contacter',
    'subscription.getStarted': 'Commencer',
    'subscription.contactDetail': 'Ce package est gere directement par le support afin d adapter l offre a votre activite.',
    'subscription.powerSellerHelp': 'Contactez le support Auradime pour un prix personnalise, la mise en avant sur la page d accueil, l acces API et un accompagnement dedie.',
    'subscription.durationDays': 'Duree en jours',
    'subscription.contactOnly': 'Package sur contact',
    'subscription.days': 'jours',
    'subscription.hidePlan': 'Masquer le package',
    'subscription.activatePlan': 'Activer le package',
    'subscription.noticeWarning': 'Action requise',
    'subscription.noticeCritical': 'Restreint',
    'subscription.title': 'Activez votre espace',
    'subscription.description': 'Ce role necessite un package actif avant d utiliser les outils du tableau de bord. Votre abonnement est verifie cote serveur.',
    'subscription.activeToast': 'Abonnement actif.',
    'subscription.loadFailed': 'Impossible de charger l abonnement.',
    'subscription.phoneRequired': 'Le numero de telephone est requis.',
    'subscription.activated': 'Abonnement active.',
    'subscription.requestSent': 'Demande de paiement envoyee.',
    'subscription.paymentFailed': 'Paiement de l abonnement echoue.',
    'subscription.alreadyActive': 'Votre abonnement est actif',
    'subscription.alreadyActiveDetail': 'Vous pouvez continuer vers votre tableau de bord et utiliser vos fonctionnalites.',
    'subscription.continueDashboard': 'Continuer',
    'subscription.payTitle': 'Paiement',
    'subscription.payDetail': 'Choisissez la methode la plus simple pour vous.',
    'subscription.wallet': 'Aura Wallet',
    'subscription.mobileMoney': 'Mobile money / carte',
    'subscription.collectionFee': 'Les frais de collecte sont ajoutes seulement pour une collecte externe.',
    'subscription.phone': 'Numero de telephone',
    'subscription.secureCheck': 'L acces est verifie cote serveur sur chaque requete protegee.',
    'subscription.activateButton': 'Activer le package',
    'subscription.adminTitle': 'Controle des abonnements',
    'subscription.adminSubtitle': 'Gerez les roles bloques, packages, abonnes et revenus d abonnement.',
    'subscription.adminLoadFailed': 'Impossible de charger les abonnements.',
    'subscription.requirementsSaved': 'Exigences d abonnement enregistrees.',
    'subscription.saveFailed': 'Impossible d enregistrer les changements.',
    'subscription.planNameRequired': 'Le nom du plan est requis.',
    'subscription.planSaved': 'Plan enregistre.',
    'subscription.subscriptionUpdated': 'Abonnement mis a jour.',
    'subscription.activeSubscribers': 'Abonnes actifs',
    'subscription.revenue': 'Revenu abonnements',
    'subscription.pending': 'Paiements en attente',
    'subscription.activePlans': 'Plans actifs',
    'subscription.graceUsers': 'Utilisateurs en grace',
    'subscription.limitedUsers': 'Acces limites',
    'subscription.graceDays': 'Jours de grace',
    'subscription.graceTitle': 'Periode de grace active',
    'subscription.graceDetail': 'Vous pouvez continuer a utiliser votre espace pendant cette periode. Activez un package avant la fin pour garder l acces complet.',
    'subscription.limitedTitle': 'Mode acces limite',
    'subscription.limitedDetail': 'Vous pouvez encore voir votre tableau de bord, mais les actions protegees sont en pause jusqu a l activation d un package.',
    'subscription.subscribeCta': 'S abonner',
    'subscription.startDate': 'Date de debut',
    'subscription.expiryDate': 'Date d expiration',
    'subscription.roleRequirements': 'Exigences par role',
    'subscription.roleRequirementsDetail': 'Admin n est jamais bloque. Activez seulement les roles qui doivent payer avant d utiliser leurs outils.',
    'subscription.editPlan': 'Modifier le plan',
    'subscription.newPlan': 'Nouveau plan',
    'subscription.planName': 'Nom du plan',
    'subscription.descriptionField': 'Description',
    'subscription.oneTime': 'Une fois',
    'subscription.monthly': 'Mensuel',
    'subscription.yearly': 'Annuel',
    'subscription.featuresHelp': 'Une fonctionnalite par ligne',
    'subscription.savePlan': 'Enregistrer le plan',
    'subscription.plans': 'Plans',
    'subscription.subscribers': 'Abonnes',
    'subscription.subscribersDetail': 'Historique recent des abonnements et paiements.',
    'subscription.plan': 'Plan',
    'subscription.noSubscribers': 'Aucun abonne pour l instant.',
    'subscription.manualRequired': 'ID utilisateur et plan requis.',
    'subscription.manualActivation': 'Activation manuelle',
    'subscription.manualActivationDetail': 'Activez un package pour un utilisateur par ID lorsque le support confirme le paiement ou accorde l acces.',
    'subscription.userId': 'ID utilisateur',
    'subscription.choosePlan': 'Choisir un plan',
    'subscription.activateUser': 'Activer utilisateur',
    'wallet.availableBalance': 'Solde disponible',
    'wallet.secureAccount': 'Compte securise',
    'wallet.available': 'Disponible',
    'wallet.availableToSpend': 'Disponible a depenser',
    'wallet.inEscrow': 'En sequestre',
    'wallet.heldInEscrow': 'Fonds bloques',
    'wallet.successful': 'Reussis',
    'wallet.failed': 'Echoues',
    'wallet.paymentsDeclined': 'Paiements refuses',
    'wallet.depositMoney': 'Ajouter de l argent',
    'wallet.withdrawMoney': 'Retirer de l argent',
    'wallet.transactionHistory': 'Historique des transactions',
    'wallet.realTimeHistory': 'Historique en temps reel',
    'wallet.noRecords': 'Aucun enregistrement {type} trouve',
    'wallet.withdrawal': 'retrait',
    'wallet.checking': 'Verification...',
    'wallet.recheckPayment': 'Reverifier le paiement',
    'wallet.tab.all': 'tout',
    'wallet.tab.in': 'entrees',
    'wallet.tab.out': 'sorties',
    'wallet.tab.withdrawals': 'retraits',
    'overtime.shopByCategory': 'Acheter par categorie',
    'overtime.browse': 'Parcourir',
    'overtime.explore': 'Explorer',
    'overtime.exploreCollection': 'Explorer la collection',
    'overtime.topRatedVendors': 'Vendeurs les mieux notes',
    'overtime.vendorFallback': 'Decouvrez des produits premium de ce vendeur de confiance.',
    'shop.exploreStores': 'Explorer les boutiques',
    'shop.globalDiscovery': 'Decouverte globale',
    'product.notFound': 'Produit introuvable',
    'product.backToShop': 'Retour a la boutique',
    'product.home': 'Accueil',
    'product.shop': 'Boutique',
    'product.addedWishlist': 'Ajoute aux favoris',
    'product.removedWishlist': 'Retire des favoris',
    'product.linkCopied': 'Lien copie !',
    'product.cartFailed': 'Mise a jour du panier echouee',
    'product.addToCart': 'Ajouter au panier',
    'product.unableSeller': 'Impossible de joindre le vendeur.',
    'product.verified': 'Verifie par Aura market',
    'product.new': 'Nouveau',
    'product.available': '{count} disponible',
    'product.selectOption': 'Choisir {name}',
    'product.description': 'Description',
    'product.reviews': 'Avis',
    'product.seeAll': 'Voir tout',
    'product.noReviews': 'Aucun avis pour l instant.',
    'product.buyer': 'Acheteur',
    'product.verifiedPurchase': 'Achat verifie',
    'product.quantity': 'Quantite',
    'product.yourItem': 'Votre article publie',
    'product.currentlyOut': 'Actuellement en rupture',
    'product.deliveryReturns': 'Livraison et retours',
    'product.expressDelivery': 'Livraison express',
    'product.deliveryWindow': '24-48h dans les grandes villes',
    'product.freeReturns': 'Retours gratuits',
    'product.returnPolicy': 'Retour facile sous 7 jours',
    'product.soldBy': 'Vendu par',
    'product.rating': 'Note',
    'product.visitStore': 'Voir la boutique',
    'product.details': 'Details',
    'product.specifications': 'Specifications',
    'product.category': 'Categorie',
    'product.brand': 'Marque',
    'product.condition': 'Etat',
    'product.sku': 'SKU',
    'product.seller': 'Vendeur',
    'product.general': 'General',
    'product.brandNew': 'Neuf',
    'product.unitsAvailable': '{count} unites disponibles',
    'product.officialStore': 'Boutique officielle',
    'product.related': 'Vous aimerez aussi',
    'product.viewAll': 'Voir tout',
    'search.productsPlaceholder': 'Rechercher des produits premium...',
    'search.ordersPlaceholder': 'Rechercher par commande ou produit',
    'role.customer': 'client',
    'role.vendor': 'vendeur',
    'role.logistics': 'logistique',
    'orders.title': 'Commandes',
    'orders.vendorHelp': 'Suivez vos achats et les ventes de votre boutique.',
    'orders.customerHelp': 'Consultez et suivez votre historique de commandes.',
    'orders.refresh': 'Actualiser',
    'orders.myPurchases': 'Mes achats',
    'orders.mySales': 'Mes ventes',
    'orders.total': 'Total',
    'orders.active': 'Actives',
    'orders.completed': 'Terminees',
    'orders.issues': 'Problemes',
    'orders.history': 'Historique',
    'orders.shown': '{count} affiches',
    'orders.loading': 'Chargement des commandes...',
    'orders.none': 'Aucune commande trouvee.',
    'orders.item': 'article',
    'orders.items': 'articles',
    'status.all': 'Tout',
    'status.placed': 'Placee',
    'status.processing': 'En traitement',
    'status.shipped': 'Expediee',
    'status.completed': 'Terminee',
    'status.failed': 'Echouee',
    'status.cancelled': 'Annulee',
    'status.refunded': 'Remboursee',
    'status.delivered': 'Livree',
    'status.pending': 'En attente',
    'status.refundedToWallet': 'Rembourse sur wallet',
    'status.refundPending': 'Remboursement en attente',
    'status.walletCredited': 'Wallet credite',
    'status.payOnDelivery': 'Paiement a la livraison',
    'status.paid': 'Paye',
    'status.inStock': 'En stock',
    'sort.newest': 'Nouveautes',
    'sort.priceLowHigh': 'Prix croissant',
    'sort.priceHighLow': 'Prix decroissant',
    'sort.highestRated': 'Mieux notes',
    'price.under5000': 'Moins de 5 000 XAF',
    'price.5000to10000': '5 000 - 10 000 XAF',
    'price.10000to50000': '10 000 - 50 000 XAF',
    'price.over50000': 'Plus de 50 000 XAF',
    'label.electronics': 'Electronique',
    'label.mens.clothing': 'Vetements homme',
    'label.health.and.fitness': 'Sante et fitness',
    'label.laptops': 'Ordinateurs portables',
    'label.smartwatches': 'Montres connectees',
    'label.shoulder.bags': 'Sacs a bandouliere',
    'label.hoodies': 'Sweats a capuche',
    'label.charcoal.grills': 'Barbecues au charbon',
    'label.keyboards.and.mice': 'Claviers et souris',
    'label.books': 'Livres',
    'label.printed.books': 'Livres imprimes',
    'label.fiction': 'Fiction',
    'label.non.fiction': 'Non-fiction',
    'label.childrens.books': 'Livres enfants',
    'label.graphic.novels': 'Romans graphiques',
    'label.poetry': 'Poesie',
    'label.home.and.kitchen': 'Maison et cuisine',
    'label.fashion.and.lifestyle': 'Mode et lifestyle',
    'label.beauty.and.personal.care': 'Beaute et soins',
    'label.kids.and.baby.clothing': 'Vetements enfants et bebe',
    'label.sports.and.outdoors': 'Sports et exterieur',
    'label.flash.sale': 'Vente flash',
    'label.new.arrival': 'Nouveaute',
    'label.available.for.delivery': 'Disponible en livraison',
    'label.looking.for': 'Recherche',
    'label.store.update': 'Info boutique',
    'label.moment': 'Moment',
    'label.review.and.recommend': 'Avis et recommandation',
    'label.trade.swap': 'Echange',
    'label.service.offer': 'Offre de service',
    'label.order.update': 'Suivi commande',
    'label.alert': 'Alerte',
    'label.community': 'Communaute',
    'label.best.sellers': 'Meilleures ventes',
    'label.top.rated.vendors': 'Vendeurs les mieux notes',
    'label.featured.products': 'Produits en vedette',
    'label.featured': 'En vedette',
    'label.hype.drop.energy': 'Energie du lancement',
    'label.the.drop.you.ve.been.waiting.for.auradime.is.live': 'Le lancement que vous attendiez - AuraDime est en ligne.',
    'label.your.aura.found.its.match.auradime.is.here': 'Votre aura a trouve sa plateforme. AuraDime est la.',
    'label.community.vibe': 'Ambiance communaute',
    'label.explore.collection': 'Explorer la collection',
  },
};

const readStoredLanguage = () => {
  if (typeof window === 'undefined') return 'en';
  try {
    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (stored) return normalizeLanguage(stored);

    const cookieMatch = document.cookie
      ?.split('; ')
      .find((row) => row.startsWith(`${STORAGE_KEY}=`))
      ?.split('=')[1];
    if (cookieMatch) return normalizeLanguage(decodeURIComponent(cookieMatch));

    const browserLanguage = navigator.languages?.[0] || navigator.language || '';
    return browserLanguage.toLowerCase().startsWith('fr') ? 'fr' : 'en';
  } catch {
    return 'en';
  }
};

const translations = {
  en: {
    'common.login': 'Login',
    'common.search': 'Search',
    'common.clearSearch': 'Clear search',
    'search.placeholder': 'Search products and stores',
    'nav.shop': 'Shop',
    'nav.vendors': 'Vendors',
    'nav.stories': 'Stories',
    'nav.story': 'Story',
    'nav.overtime': 'Overtime',
    'nav.profile': 'Profile',
    'nav.dashboard': 'Dashboard',
    'bottomNav.shop': 'Shop',
    'bottomNav.vendors': 'Vendors',
    'bottomNav.stories': 'Stories',
    'bottomNav.story': 'Story',
    'bottomNav.overtime': 'Overtime',
    'bottomNav.profile': 'Profile',
    'bottomNav.dashboard': 'Dash',
    'settings.title': 'Account Settings',
    'settings.identity': 'Identity Parameters',
    'settings.fullName': 'Full Name',
    'settings.phoneNumber': 'Phone Number',
    'settings.email': 'Email',
    'settings.language': 'Language',
    'settings.languageHelp': 'Choose the language used across Auradime on this device.',
    'settings.languageSaved': 'Language updated.',
    'settings.languageFailed': 'Language saved on this device. Account sync failed.',
    'settings.saving': 'Synchronizing state...',
    'settings.saveIdentity': 'Save identity configuration',
    'login.tagline': 'Secure email verification',
    'login.welcome': 'Welcome to Aura Dime',
    'login.emailHelp': 'Enter your email and we will send a verification code.',
    'login.sendCode': 'Send code',
    'login.enterCode': 'Enter code',
    'login.haveCode': 'I already have a code',
    'login.checkEmail': 'Check your email',
    'login.changeEmail': 'Change email',
    'login.verifyCode': 'Verify code',
    'login.resendCode': 'Resend code',
    'login.resendIn': 'Resend code in {seconds}s',
    'login.createAccount': 'Create your account',
    'login.fullNameRequired': 'Full name is required.',
    'login.phoneRequired': 'Phone number is required.',
    'login.fullName': 'Full name',
    'login.phoneNumber': 'Phone number',
    'login.continueAs': 'Continue as',
    'login.onboardingHint': 'After this, we will open the guided onboarding flow to finish your role setup.',
    'login.continueOnboarding': 'Continue to onboarding',
    'login.legalPrefix': "By continuing, you acknowledge Auradime's",
    'login.terms': 'Terms',
    'login.privacy': 'Privacy Policy',
    'login.cookies': 'Cookie Policy',
    'login.legalMiddle': 'and',
    'login.legalSuffix': 'plus the marketplace policies in the',
    'login.legalCenter': 'Legal Center',
    'legal.backToLogin': 'Back to login',
    'legal.cameroonPolicy': 'Cameroon marketplace policy',
    'legal.center': 'Legal Center',
    'legal.lastUpdated': 'Last updated',
    'legal.jurisdiction': 'Jurisdiction',
    'legal.contact': 'Contact',
    'legal.morePolicies': 'More policies',
    'legal.disclaimer': 'This page is operational policy information for AuraDime and is not a substitute for legal advice. A qualified Cameroon lawyer should review the final published policies for regulatory completeness.',
    'legal.link.terms': 'Terms',
    'legal.link.privacy': 'Privacy',
    'legal.link.cookies': 'Cookies',
    'legal.link.refundPolicy': 'Refunds',
    'legal.link.vendorPolicy': 'Vendors',
    'legal.link.logisticsPolicy': 'Logistics',
    'legal.link.prohibitedItems': 'Prohibited Items',
    'legal.link.disputePolicy': 'Disputes',
    'legal.link.accountDeletion': 'Account Deletion',
    'login.existingCodeNotice': 'Enter the code we already sent. You can request a new one when the timer ends.',
    'login.requestTimeout': 'The code request is taking too long. Please check your connection or try another network.',
    'login.codeArrivedNotice': 'If the code arrived, enter it here. You can resend when the timer ends.',
    'login.codeSent': 'Verification code sent',
    'login.verifyTimeout': 'Verification is taking too long. Please try again.',
    'login.setupTimeout': 'Account setup is taking too long. Please try again.',
    'tabs.general': 'Profile',
    'tabs.orders': 'Orders',
    'tabs.wishlist': 'Wishlist',
    'tabs.security': 'Security',
    'tabs.close-account': 'Close account',
    'tabs.network': 'Network',
    'tabs.audience': 'Audience',
    'tabs.store': 'Store',
    'tabs.fleet': 'Fleet',
    'tabs.governance': 'Governance',
    'tabs.kyc': 'Verification',
    'tabs.notifications': 'Alerts',
    'tabs.advanced': 'Advanced',
    ...SYSTEM_TRANSLATIONS.en,
  },
  fr: {
    'common.login': 'Connexion',
    'common.search': 'Rechercher',
    'common.clearSearch': 'Effacer la recherche',
    'search.placeholder': 'Rechercher des produits et boutiques',
    'nav.shop': 'Boutique',
    'nav.vendors': 'Vendeurs',
    'nav.stories': 'Stories',
    'nav.story': 'Story',
    'nav.overtime': 'Overtime',
    'nav.profile': 'Profil',
    'nav.dashboard': 'Tableau',
    'bottomNav.shop': 'Shop',
    'bottomNav.vendors': 'Vendeurs',
    'bottomNav.stories': 'Stories',
    'bottomNav.story': 'Story',
    'bottomNav.overtime': 'Overtime',
    'bottomNav.profile': 'Profil',
    'bottomNav.dashboard': 'Tableau',
    'settings.title': 'Paramètres du compte',
    'settings.identity': 'Informations d’identité',
    'settings.fullName': 'Nom complet',
    'settings.phoneNumber': 'Numéro de téléphone',
    'settings.email': 'E-mail',
    'settings.language': 'Langue',
    'settings.languageHelp': 'Choisissez la langue utilisée sur Auradime sur cet appareil.',
    'settings.languageSaved': 'Langue mise à jour.',
    'settings.languageFailed': 'Langue enregistrée sur cet appareil. Synchronisation du compte échouée.',
    'settings.saving': 'Synchronisation...',
    'settings.saveIdentity': 'Enregistrer les informations',
    'login.tagline': 'Vérification sécurisée par e-mail',
    'login.welcome': 'Bienvenue sur Aura Dime',
    'login.emailHelp': 'Entrez votre e-mail et nous vous enverrons un code de vérification.',
    'login.sendCode': 'Envoyer le code',
    'login.enterCode': 'Entrer le code',
    'login.haveCode': "J’ai déjà un code",
    'login.checkEmail': 'Vérifiez votre e-mail',
    'login.changeEmail': "Changer l’e-mail",
    'login.verifyCode': 'Vérifier le code',
    'login.resendCode': 'Renvoyer le code',
    'login.resendIn': 'Renvoyer le code dans {seconds}s',
    'login.createAccount': 'Créer votre compte',
    'login.fullNameRequired': 'Le nom complet est requis.',
    'login.phoneRequired': 'Le numéro de téléphone est requis.',
    'login.fullName': 'Nom complet',
    'login.phoneNumber': 'Numéro de téléphone',
    'login.continueAs': 'Continuer comme',
    'login.onboardingHint': 'Ensuite, nous ouvrirons le parcours guidé pour terminer la configuration de votre rôle.',
    'login.continueOnboarding': 'Continuer vers l’onboarding',
    'login.legalPrefix': 'En continuant, vous acceptez les',
    'login.terms': 'Conditions',
    'login.privacy': 'Politique de confidentialité',
    'login.cookies': 'Politique des cookies',
    'login.legalMiddle': 'et',
    'login.legalSuffix': 'ainsi que les règles du marketplace dans le',
    'login.legalCenter': 'Centre légal',
    'legal.backToLogin': 'Retour a la connexion',
    'legal.cameroonPolicy': 'Politique marketplace Cameroun',
    'legal.center': 'Centre legal',
    'legal.lastUpdated': 'Derniere mise a jour',
    'legal.jurisdiction': 'Juridiction',
    'legal.contact': 'Contact',
    'legal.morePolicies': 'Autres politiques',
    'legal.disclaimer': 'Cette page fournit des informations de politique operationnelle pour AuraDime et ne remplace pas un avis juridique. Un avocat qualifie au Cameroun doit relire les politiques finales publiees pour verifier leur conformite.',
    'legal.link.terms': 'Conditions',
    'legal.link.privacy': 'Confidentialite',
    'legal.link.cookies': 'Cookies',
    'legal.link.refundPolicy': 'Remboursements',
    'legal.link.vendorPolicy': 'Vendeurs',
    'legal.link.logisticsPolicy': 'Logistique',
    'legal.link.prohibitedItems': 'Articles interdits',
    'legal.link.disputePolicy': 'Litiges',
    'legal.link.accountDeletion': 'Suppression du compte',
    'login.existingCodeNotice': 'Entrez le code déjà envoyé. Vous pourrez demander un nouveau code à la fin du compte à rebours.',
    'login.requestTimeout': 'La demande de code prend trop de temps. Vérifiez votre connexion ou essayez un autre réseau.',
    'login.codeArrivedNotice': 'Si le code est arrivé, entrez-le ici. Vous pourrez le renvoyer à la fin du compte à rebours.',
    'login.codeSent': 'Code de vérification envoyé',
    'login.verifyTimeout': 'La vérification prend trop de temps. Veuillez réessayer.',
    'login.setupTimeout': 'La création du compte prend trop de temps. Veuillez réessayer.',
    'tabs.general': 'Profil',
    'tabs.orders': 'Commandes',
    'tabs.wishlist': 'Favoris',
    'tabs.security': 'Sécurité',
    'tabs.close-account': 'Fermer le compte',
    'tabs.network': 'Réseau',
    'tabs.audience': 'Audience',
    'tabs.store': 'Boutique',
    'tabs.fleet': 'Flotte',
    'tabs.governance': 'Gouvernance',
    'tabs.kyc': 'Vérification',
    'tabs.notifications': 'Alertes',
    'tabs.advanced': 'Avancé',
    ...SYSTEM_TRANSLATIONS.fr,
  },
};

const LEGAL_TEXT_TRANSLATIONS_FR = {
  'Back to login': 'Retour a la connexion',
  'Cameroon marketplace policy': 'Politique marketplace Cameroun',
  'Legal Center': 'Centre legal',
  'Last updated:': 'Derniere mise a jour :',
  'Jurisdiction:': 'Juridiction :',
  'Contact': 'Contact',
  'More policies': 'Autres politiques',
  'Terms': 'Conditions',
  'Privacy': 'Confidentialite',
  'Cookies': 'Cookies',
  'Refunds': 'Remboursements',
  'Prohibited Items': 'Articles interdits',
  'Account Deletion': 'Suppression du compte',
  'AuraDime Marketplace Terms of Service': 'Conditions d’utilisation du marketplace AuraDime',
  'The rules for using AuraDime as a customer, vendor, or logistics partner.': 'Les regles d’utilisation d’AuraDime pour les clients, vendeurs et partenaires logistiques.',
  'AuraDime Privacy Policy': 'Politique de confidentialite AuraDime',
  'How AuraDime collects, uses, shares, protects, and retains user data.': 'Comment AuraDime collecte, utilise, partage, protege et conserve les donnees des utilisateurs.',
  'AuraDime Cookie Policy': 'Politique de cookies AuraDime',
  'How AuraDime uses cookies, local storage, and app storage for login, cart, security, and preferences.': 'Comment AuraDime utilise les cookies, le stockage local et le stockage de l’application pour la connexion, le panier, la securite et les preferences.',
  'AuraDime Refund and Cancellation Policy': 'Politique de remboursement et d’annulation AuraDime',
  'How paid orders, unpaid orders, escrow releases, failed payments, and refunds are handled.': 'Comment sont geres les commandes payees, non payees, les liberations de sequestre, les paiements echoues et les remboursements.',
  'AuraDime Vendor Policy': 'Politique vendeur AuraDime',
  'Rules for stores, listings, pricing, fulfillment, KYC, payouts, and vendor conduct.': 'Regles concernant les boutiques, annonces, prix, execution, KYC, paiements et conduite des vendeurs.',
  'AuraDime Logistics Partner Policy': 'Politique partenaire logistique AuraDime',
  'Rules for delivery partners, service zones, shipment updates, proof of delivery, and payouts.': 'Regles pour les partenaires de livraison, zones de service, mises a jour d’expedition, preuves de livraison et paiements.',
  'AuraDime Prohibited Items Policy': 'Politique des articles interdits AuraDime',
  'Products and services that cannot be listed, bought, or promoted on AuraDime.': 'Produits et services qui ne peuvent pas etre listes, achetes ou promus sur AuraDime.',
  'AuraDime Dispute and Escrow Policy': 'Politique de litiges et de sequestre AuraDime',
  'How AuraDime reviews order disputes, delivery issues, evidence, refunds, and escrow releases.': 'Comment AuraDime examine les litiges de commande, problemes de livraison, preuves, remboursements et liberations de sequestre.',
  'AuraDime Account Deletion Policy': 'Politique de suppression de compte AuraDime',
  'What happens when a user permanently deletes an AuraDime account.': 'Ce qui se passe lorsqu’un utilisateur supprime definitivement son compte AuraDime.',
  '1. Introduction': '1. Introduction',
  '2. Eligibility': '2. Eligibilite',
  '3. AuraDime role as a marketplace': '3. Role d’AuraDime comme marketplace',
  '4. User accounts and sessions': '4. Comptes utilisateurs et sessions',
  '5. Customer terms': '5. Conditions clients',
  '6. Vendor terms': '6. Conditions vendeurs',
  '7. Logistics partner terms': '7. Conditions partenaires logistiques',
  '8. Payments, wallet, escrow, and withdrawals': '8. Paiements, wallet, sequestre et retraits',
  '9. Prohibited conduct': '9. Conduite interdite',
  '10. Disputes and admin decisions': '10. Litiges et decisions admin',
  '11. Suspension and termination': '11. Suspension et resiliation',
  '12. Liability': '12. Responsabilite',
  '13. Governing law': '13. Droit applicable',
  '14. Changes': '14. Modifications',
  '1. Data we collect': '1. Donnees collectees',
  '2. How we use data': '2. Utilisation des donnees',
  '3. Data sharing': '3. Partage des donnees',
  '4. Storage and security': '4. Stockage et securite',
  '5. Retention': '5. Conservation',
  '6. Your rights': '6. Vos droits',
  '7. Children': '7. Enfants',
  '8. International transfers': '8. Transferts internationaux',
  '1. What cookies are': '1. Que sont les cookies',
  '2. Storage we use': '2. Stockage utilise',
  '3. Your choices': '3. Vos choix',
  '1. Paid order cancellation': '1. Annulation d’une commande payee',
  '2. Unpaid and failed orders': '2. Commandes non payees et echouees',
  '3. Refund eligibility': '3. Conditions de remboursement',
  '4. Non-refundable situations': '4. Situations non remboursables',
  '5. Processing': '5. Traitement',
  '1. Vendor verification': '1. Verification vendeur',
  '2. Listings and pricing': '2. Annonces et prix',
  '3. Fulfillment': '3. Execution',
  '4. Wallet and payouts': '4. Wallet et paiements',
  '5. Store standards': '5. Standards boutique',
  '1. Verification and service zones': '1. Verification et zones de service',
  '2. Shipment handling': '2. Gestion des expeditions',
  '3. Failed delivery': '3. Livraison echouee',
  '4. Payouts and conduct': '4. Paiements et conduite',
  '1. Prohibited products': '1. Produits interdits',
  '2. Restricted products': '2. Produits restreints',
  '3. Enforcement': '3. Application',
  '1. When disputes can be raised': '1. Quand ouvrir un litige',
  '2. Escrow': '2. Sequestre',
  '3. Evidence': '3. Preuves',
  '4. Admin outcomes': '4. Decisions admin',
  '5. Appeals': '5. Appels',
  '1. Permanent deletion': '1. Suppression definitive',
  '2. What is deleted or disabled': '2. Ce qui est supprime ou desactive',
  '3. What may be retained': '3. Ce qui peut etre conserve',
  '4. Wallet and pending orders': '4. Wallet et commandes en attente',
  '5. Reviews and public content': '5. Avis et contenu public',
  'Identity': 'Identite',
  'Address': 'Adresse',
  'Communications': 'Communications',
  'Technical': 'Technique',
  'Usage': 'Utilisation',
  'Strictly necessary': 'Strictement necessaire',
  'Functional': 'Fonctionnel',
  'Analytics and performance': 'Analyses et performance',
  'Offline app data': 'Donnees hors ligne',
  'Push notifications': 'Notifications push',
  'This page is operational policy information for AuraDime and is not a substitute for legal advice. A qualified Cameroon lawyer should review the final published policies for regulatory completeness.': 'Cette page fournit des informations de politique operationnelle pour AuraDime et ne remplace pas un avis juridique. Un avocat qualifie au Cameroun doit relire les politiques finales publiees pour verifier leur conformite.',
  'To confirm deletion, the user may be required to type DELETE. This action is intended to be irreversible.': 'Pour confirmer la suppression, l’utilisateur peut devoir taper DELETE ou SUPPRIMER selon la langue active. Cette action est irreversible.',
  'To confirm deletion, type DELETE': 'Pour confirmer la suppression, tapez DELETE',
  'To confirm deletion, type SUPPRIMER': 'Pour confirmer la suppression, tapez SUPPRIMER',
  'Cameroon': 'Cameroun',
};

const NOTIFICATION_TEXT_TRANSLATIONS_FR = {
  'Order placed': 'Commande passee',
  'Order updated': 'Commande mise a jour',
  'Order Confirmed': 'Commande confirmee',
  'Order Payment Confirmed': 'Paiement de commande confirme',
  'Order Paid & Confirmed': 'Commande payee et confirmee',
  'New Order Received': 'Nouvelle commande recue',
  'New Shipment Assigned': 'Nouvelle expedition assignee',
  'Payment failed': 'Paiement echoue',
  'Payment Confirmed': 'Paiement confirme',
  'Wallet Credited': 'Wallet credite',
  'Withdrawal Request Submitted': 'Demande de retrait envoyee',
  'Withdrawal Successful': 'Retrait reussi',
  'Withdrawal Failed': 'Retrait echoue',
  'Withdrawal Request Rejected': 'Demande de retrait rejetee',
  'Payout Failed': 'Paiement echoue',
  'Funds Released': 'Fonds liberes',
  'Order Completed': 'Commande terminee',
  'Order Cancelled': 'Commande annulee',
  'Order Cancelled & Refunded': 'Commande annulee et remboursee',
  'Shipment Update': 'Mise a jour expedition',
  'Your order has been delivered': 'Votre commande a ete livree',
  'Package Delivered': 'Colis livre',
  'Dispute Raised': 'Litige ouvert',
  'Verification Required': 'Verification requise',
  'Identity Verified': 'Identite verifiee',
  'KYC Rejected': 'KYC rejete',
  'New Product Question': 'Nouvelle question produit',
  'Question Answered': 'Question repondue',
  'New Status Reaction ❤️': 'Nouvelle reaction au statut ❤️',
};

const ROLE_FLOW_TRANSLATIONS_FR = {
  'Account': 'Compte',
  'Full Name': 'Nom complet',
  'Role': 'Role',
  'Address': 'Adresse',
  'City': 'Ville',
  'Zone': 'Zone',
  'Quartier': 'Quartier',
  'Delivery notes or nearest landmark': 'Notes de livraison ou repere le plus proche',
  'Edit profile': 'Modifier le profil',
  'Save changes': 'Enregistrer les modifications',
  'Delete Account': 'Supprimer le compte',
  'Close account': 'Fermer le compte',
  'Type DELETE to confirm': 'Tapez DELETE pour confirmer',
  'Type SUPPRIMER to confirm': 'Tapez SUPPRIMER pour confirmer',
  'Close account permanently': 'Fermer le compte definitivement',
  'Deletes your profile, tokens, carts, messages, listings, follows, notifications, and account-linked records. This cannot be undone.': 'Supprime votre profil, vos jetons, paniers, messages, annonces, abonnements, notifications et donnees liees au compte. Cette action est irreversible.',
  'This action is irreversible': 'Cette action est irreversible',
  'Search products': 'Rechercher des produits',
  'Search stores': 'Rechercher des boutiques',
  'Category': 'Categorie',
  'Filters': 'Filtres',
  'Sort by': 'Trier par',
  'Add to cart': 'Ajouter au panier',
  'View store': 'Voir la boutique',
  'View product': 'Voir le produit',
  'Quantity': 'Quantite',
  'Delivery fee': 'Frais de livraison',
  'Proceed to checkout': 'Passer a la caisse',
  'Your cart is empty': 'Votre panier est vide',
  'No products in your store': 'Aucun produit dans votre boutique',
  'No products found': 'Aucun produit trouve',
  'No messages': 'Aucun message',
  'No messages yet. Follow vendors to chat!': 'Aucun message pour le moment. Suivez des vendeurs pour discuter !',
  'No notifications': 'Aucune notification',
  'No results found': 'Aucun resultat trouve',
  'No results found.': 'Aucun resultat trouve.',
  'No products in this category': 'Aucun produit dans cette categorie',
  'Discovery is syncing.': 'Discovery se synchronise.',
  'Your wishlist is empty': 'Votre liste de favoris est vide',
  'No Followed Vendors': 'Aucun vendeur suivi',
  'No Followers Yet': 'Aucun abonne pour le moment',
  'Payment pending': 'Paiement en attente',
  'Awaiting payment': 'Paiement en attente',
  'Awaiting gateway confirmation.': 'Confirmation du paiement en attente.',
  'Session expired': 'Session expiree',
  'Your session has expired. Please verify your email again.': 'Votre session a expire. Veuillez verifier votre e-mail a nouveau.',
  'You are offline': 'Vous etes hors ligne',
  'Offline mode': 'Mode hors ligne',
  'Showing saved data while your connection is unstable.': 'Affichage des donnees enregistrees pendant que la connexion est instable.',
  'Network Error': 'Erreur reseau',
  'Please enter a valid email': 'Veuillez saisir un e-mail valide',
  'Please enter a valid email address': 'Veuillez saisir une adresse e-mail valide',
  'Please enter a valid email address.': 'Veuillez saisir une adresse e-mail valide.',
  'This field is required': 'Ce champ est obligatoire',
  'This field is required.': 'Ce champ est obligatoire.',
  'Please fill all required fields.': 'Veuillez remplir tous les champs obligatoires.',
  'OTP expired, please request a new code': 'OTP expire, veuillez demander un nouveau code',
  'Invalid OTP': 'OTP invalide',
  'Invalid code': 'Code invalide',
  'Verification failed': 'Verification echouee',
  'Order cannot be cancelled — fulfillment has started': 'La commande ne peut pas etre annulee — l’execution a commence',
  'This order has already moved into fulfilment and cannot be cancelled here.': 'Cette commande est deja en cours d’execution et ne peut plus etre annulee ici.',
  'Paid orders can only be cancelled within 30 minutes of checkout.': 'Les commandes payees ne peuvent etre annulees que dans les 30 minutes apres le paiement.',
  'Withdrawal limit exceeded': 'Limite de retrait depassee',
  'File too large': 'Fichier trop volumineux',
  'File too large. Maximum size is 30MB': 'Fichier trop volumineux. Taille maximale : 30 Mo',
  'Unsupported file type': 'Type de fichier non pris en charge',
  'Phone number is required.': 'Le numero de telephone est obligatoire.',
  'Phone number is required for Mobile Money withdrawal.': 'Le numero de telephone est obligatoire pour un retrait Mobile Money.',
  'Recipient first name, last name, and country are required.': 'Le prenom, le nom et le pays du beneficiaire sont obligatoires.',
  'Bank code and account number are required for bank withdrawal.': 'Le code banque et le numero de compte sont obligatoires pour un retrait bancaire.',
  'A rejection reason (min 5 characters) is required.': 'Un motif de rejet est obligatoire (5 caracteres minimum).',
  'Reason for failure is required.': 'Le motif de l’echec est obligatoire.',
  'Vendor access required.': 'Acces vendeur requis.',
  'Verification is required': 'Verification requise',
  'Verification required': 'Verification requise',
  'Verification is required before this action can be completed.': 'Une verification est requise avant d’effectuer cette action.',
  'Authentication required': 'Authentification requise',
  'Sign in required': 'Connexion requise',
  'Remove item': 'Retirer l’article',
  'Delivery Details': 'Details de livraison',
  'Consignee Name': 'Nom du destinataire',
  'Comms Protocol (Phone)': 'Contact telephone',
  'Handshake Email': 'E-mail',
  'Delivery Quartier (Zone)': 'Quartier de livraison',
  'Precise Landing Details (Build/Street No.)': 'Details precis de livraison (batiment/rue)',
  'Logistics Partner': 'Partenaire logistique',
  'Delivery Option': 'Option de livraison',
  'Vendor managed': 'Gere par le vendeur',
  'No logistics agency fee. The vendor arranges delivery directly.': 'Aucun frais d’agence logistique. Le vendeur organise la livraison directement.',
  'Payment Strategy': 'Mode de paiement',
  'Payment method': 'Methode de paiement',
  'Pay from your Auradime wallet balance.': 'Payez avec le solde de votre wallet Auradime.',
  'Mobile money collection with a 500 XAF minimum.': 'Paiement mobile money avec un minimum de 500 XAF.',
  'Settle payment when delivery is confirmed.': 'Reglez le paiement a la confirmation de livraison.',
  'Order Summary': 'Resume de commande',
  'Cart Subtotal': 'Sous-total du panier',
  'Final Total': 'Total final',
  'Place order': 'Passer la commande',
  'Consent': 'Consentement',
  'Order placed': 'Commande passee',
  'Cancel order': 'Annuler la commande',
  'Cancel & refund': 'Annuler et rembourser',
  '30-minute refund window': 'Fenetre de remboursement de 30 minutes',
  'Tracking info': 'Informations de suivi',
  'Order detail': 'Detail de commande',
  'Order details': 'Details de commande',
  'Open dispute': 'Ouvrir un litige',
  'Evidence upload': 'Televersement de preuves',
  'Upload evidence': 'Ajouter une preuve',
  'Under review': 'En cours d’examen',
  'Resolved': 'Resolue',
  'Admin decision': 'Decision admin',
  'Dispute form': 'Formulaire de litige',
  'Reason': 'Motif',
  'Notes': 'Notes',
  'Description': 'Description',
  'Deposit': 'Depot',
  'Withdraw': 'Retirer',
  'Withdraw funds': 'Retirer des fonds',
  'Request withdrawal': 'Demander un retrait',
  'Transaction history': 'Historique des transactions',
  'Credit': 'Credit',
  'Debit': 'Debit',
  'Refund': 'Remboursement',
  'Escrow': 'Sequestre',
  'Commission': 'Commission',
  'Fee breakdown': 'Details des frais',
  'Available': 'Disponible',
  'Available to spend': 'Disponible a depenser',
  'In escrow': 'En sequestre',
  'Held in escrow': 'Bloque en sequestre',
  'Successful': 'Reussi',
  'Payments declined': 'Paiements refuses',
  'Business info': 'Informations entreprise',
  'Store setup': 'Configuration boutique',
  'Store management': 'Gestion de boutique',
  'Store name': 'Nom de la boutique',
  'Store description': 'Description de la boutique',
  'Store banner': 'Banniere boutique',
  'Store logo': 'Logo boutique',
  'Pickup details': 'Details de ramassage',
  'Pickup address': 'Adresse de ramassage',
  'Operating hours': 'Heures d’ouverture',
  'Vacation mode': 'Mode vacances',
  'Store visibility': 'Visibilite boutique',
  'Product management': 'Gestion produits',
  'Add product': 'Ajouter un produit',
  'Edit product': 'Modifier le produit',
  'Product title': 'Titre du produit',
  'Long description': 'Description detaillee',
  'Stock': 'Stock',
  'Variants': 'Variantes',
  'Size': 'Taille',
  'Color': 'Couleur',
  'Images': 'Images',
  'Shipping info': 'Infos livraison',
  'Submit for approval': 'Soumettre pour approbation',
  'Approval status': 'Statut d’approbation',
  'Approved': 'Approuve',
  'Rejected': 'Rejete',
  'Hidden': 'Masque',
  'Incoming orders': 'Commandes entrantes',
  'Approve order': 'Approuver la commande',
  'Pack': 'Emballer',
  'Mark ready for pickup': 'Marquer pret pour ramassage',
  'Mark shipped': 'Marquer expedie',
  'Mark delivered': 'Marquer livre',
  'Earnings summary': 'Resume des revenus',
  'Payout history': 'Historique des paiements',
  'Sales summary': 'Resume des ventes',
  'Revenue chart': 'Graphique revenus',
  'Best-selling products': 'Produits les plus vendus',
  'Date range': 'Periode',
  'Policy acceptance': 'Acceptation des politiques',
  'Onboarding': 'Onboarding',
  'Verification prompts': 'Demandes de verification',
  'Document upload': 'Televersement de documents',
  'Document upload labels': 'Libelles de documents',
  'Approval status messages': 'Messages de statut d’approbation',
  'Rider details': 'Details livreur',
  'Driver details': 'Details chauffeur',
  'Vehicle info': 'Infos vehicule',
  'Service zone': 'Zone de service',
  'Service zones': 'Zones de service',
  'Zone / Coverage': 'Zone / Couverture',
  'Active shipments': 'Expeditions actives',
  'Shipment detail': 'Detail expedition',
  'Mark picked up': 'Marquer ramasse',
  'Mark in transit': 'Marquer en transit',
  'Report failed delivery': 'Signaler livraison echouee',
  'Mark returned': 'Marquer retourne',
  'Failed delivery': 'Livraison echouee',
  'Failed delivery reporting': 'Signalement de livraison echouee',
  'Reason selector': 'Selection du motif',
  'Customer absent': 'Client absent',
  'Wrong address': 'Mauvaise adresse',
  'Refused': 'Refuse',
  'Retry scheduling': 'Planification de nouvelle tentative',
  'Delivery fee per shipment': 'Frais de livraison par expedition',
  'Total earnings': 'Revenus totaux',
  'Escrow release status': 'Statut de liberation du sequestre',
  'Availability': 'Disponibilite',
  'Availability toggle': 'Activation disponibilite',
  'Partner profile': 'Profil partenaire',
  'User management': 'Gestion utilisateurs',
  'Account status': 'Statut compte',
  'Suspended': 'Suspendu',
  'Deleted': 'Supprime',
  'KYC review': 'Revision KYC',
  'Order management': 'Gestion commandes',
  'Manual intervention': 'Intervention manuelle',
  'Escrow release': 'Liberation sequestre',
  'Escrow hold': 'Blocage sequestre',
  'Dispute management': 'Gestion litiges',
  'Dispute queue': 'File des litiges',
  'Evidence review': 'Examen des preuves',
  'Release': 'Liberer',
  'Partial': 'Partiel',
  'Dismiss': 'Rejeter',
  'Resolution notes': 'Notes de resolution',
  'Product approvals': 'Approbations produits',
  'Approval queue': 'File d’approbation',
  'Rejection reason': 'Motif de rejet',
  'Edit controls': 'Controles de modification',
  'Hide controls': 'Controles de masquage',
  'Finance': 'Finance',
  'Transaction overview': 'Apercu transactions',
  'Withdrawal approval queue': 'File d’approbation des retraits',
  'Commission configuration': 'Configuration commissions',
  'Configuration': 'Configuration',
  'Commission rates': 'Taux de commission',
  'Payout rules': 'Regles de paiement',
  'Gateway settings': 'Parametres passerelle',
  'Broadcast notification': 'Notification diffusee',
  'Notification composer': 'Compositeur de notification',
  'Notification preferences': 'Preferences notifications',
  'Conversation list': 'Liste conversations',
  'Message input': 'Champ message',
  'Timestamps': 'Horodatages',
  'Order-linked chat context': 'Contexte chat lie a la commande',
};

const AUTO_TEXT_TRANSLATIONS_FR = {
  ...LEGAL_TEXT_TRANSLATIONS_FR,
  ...NOTIFICATION_TEXT_TRANSLATIONS_FR,
  ...ROLE_FLOW_TRANSLATIONS_FR,
  'Dashboard': 'Tableau de bord',
  'Marketplace': 'Marche',
  'Users': 'Utilisateurs',
  'Vendors': 'Vendeurs',
  'Products': 'Produits',
  'Orders': 'Commandes',
  'Messages': 'Messages',
  'System Comms': 'Communications systeme',
  'Vendor KYC': 'KYC vendeur',
  'Disputes': 'Litiges',
  'Escrow & Fees': 'Escrow et frais',
  'Withdrawals': 'Retraits',
  'Transactions': 'Transactions',
  'Shipment Node': 'Expedition',
  'Logistics Earnings': 'Revenus logistiques',
  'Analytics': 'Analyses',
  'Categories': 'Categories',
  'Reviews': 'Avis',
  'Email Logs': 'Journaux e-mail',
  'Audit Ledger': 'Journal audit',
  'CMS / Hero': 'CMS / Hero',
  'Aura Stories': 'Stories',
  'Client Ratings': 'Avis clients',
  'Wallet': 'Wallet',
  'Wishlist': 'Favoris',
  'Profile': 'Profil',
  'Security': 'Securite',
  'Network': 'Reseau',
  'Verification': 'Verification',
  'Alerts': 'Alertes',
  'Signals': 'Signaux',
  'Account Configuration': 'Configuration du compte',
  'Admin Access': 'Acces admin',
  'Vendor Premium': 'Vendeur premium',
  'Fulfillment Node': 'Centre logistique',
  'Aura Member': 'Membre Aura',
  'Standard Tier': 'Niveau standard',
  'Pro Vendor': 'Vendeur pro',
  'Logistics Ops': 'Operations logistiques',
  'Governance Mode': 'Mode gouvernance',
  'Store Active': 'Boutique active',
  'Active': 'Actif',
  'Pending': 'En attente',
  'Completed': 'Termine',
  'Failed': 'Echoue',
  'Cancelled': 'Annule',
  'Refunded': 'Rembourse',
  'Processing': 'En traitement',
  'Shipped': 'Expedie',
  'Delivered': 'Livre',
  'Paid': 'Paye',
  'Unpaid': 'Non paye',
  'All': 'Tout',
  'Search': 'Rechercher',
  'Refresh': 'Actualiser',
  'Filter': 'Filtrer',
  'Filters': 'Filtres',
  'Export': 'Exporter',
  'Edit': 'Modifier',
  'Delete': 'Supprimer',
  'Save': 'Enregistrer',
  'Cancel': 'Annuler',
  'Approve': 'Approuver',
  'Disapprove': 'Refuser',
  'Suspend': 'Suspendre',
  'View': 'Voir',
  'Details': 'Details',
  'Status': 'Statut',
  'Action': 'Action',
  'Actions': 'Actions',
  'Name': 'Nom',
  'Email': 'E-mail',
  'Phone': 'Telephone',
  'Role': 'Role',
  'Customer': 'Client',
  'Vendor': 'Vendeur',
  'Logistics': 'Logistique',
  'Admin': 'Admin',
  'Amount': 'Montant',
  'Total': 'Total',
  'Subtotal': 'Sous-total',
  'Balance': 'Solde',
  'Wallet balance': 'Solde wallet',
  'Revenue': 'Revenu',
  'Net sales': 'Ventes nettes',
  'Open orders': 'Commandes ouvertes',
  'Inventory': 'Inventaire',
  'Live': 'En direct',
  'Recent Activity': 'Activite recente',
  'Recent Orders': 'Commandes recentes',
  'Sales Growth': 'Croissance ventes',
  'Monthly revenue trends': 'Tendances mensuelles',
  'Live analysis': 'Analyse en direct',
  'No Activity': 'Aucune activite',
  'No orders yet': 'Aucune commande',
  'Product': 'Produit',
  'Order ID': 'ID commande',
  'Customer': 'Client',
  'Action': 'Action',
  'Add Product': 'Ajouter produit',
  'Launch Story': 'Publier story',
  'Store Info': 'Info boutique',
  'Find anything...': 'Rechercher...',
  'Manifests': 'Manifestes',
  'Route Pricing': 'Tarifs routes',
  'Live Tracking': 'Suivi en direct',
  'Relay Nodes': 'Noeuds relais',
  'Total Platform Volume': 'Volume total plateforme',
  'Platform Volume': 'Volume plateforme',
  'Verification Watch': 'Verification en attente',
  'Escrow Flow': 'Flux escrow',
  'Core Stability': 'Stabilite systeme',
  'Platform Uptime': 'Disponibilite plateforme',
  'Access Firewall': 'Pare-feu acces',
  'Authorization Layer': 'Couche autorisation',
  'Commission Controls': 'Controle commissions',
  'Admin Commission': 'Commission admin',
  'Escrow Commission': 'Commission escrow',
  'Percentage': 'Pourcentage',
  'Save Fees': 'Enregistrer frais',
  'Order history': 'Historique commandes',
  'Transaction data': 'Donnees transaction',
  'Transaction account': 'Compte transaction',
  'Money route': 'Route argent',
  'Linked order': 'Commande liee',
  'Order total': 'Total commande',
  'Payment': 'Paiement',
  'Shipping': 'Livraison',
  'Tracking': 'Suivi',
  'Vendor store': 'Boutique vendeur',
  'Update status': 'Modifier statut',
  'Reference': 'Reference',
  'Gateway': 'Passerelle',
  'Gateway ID': 'ID passerelle',
  'Type': 'Type',
  'Created': 'Cree',
  'Search users...': 'Rechercher utilisateurs...',
  'Search products...': 'Rechercher produits...',
  'Search orders...': 'Rechercher commandes...',
  'Search vendors...': 'Rechercher vendeurs...',
  'Search transactions...': 'Rechercher transactions...',
  'Search withdrawals...': 'Rechercher retraits...',
  'Select all': 'Tout selectionner',
  'Batch delete': 'Suppression groupee',
  'Table view': 'Vue tableau',
  'Grid view': 'Vue grille',
  'Stash': 'Panier',
  'Your Stack': 'Votre panier',
  'Estimated Total': 'Total estime',
  'Cart Preview': 'Apercu panier',
  'Inventory Empty': 'Panier vide',
  'View Cart': 'Voir le panier',
  'Checkout': 'Paiement',
  'Wait time': 'Temps d attente',
  'Security Matrix': 'Securite du compte',
  'Change Passphrase': 'Changer le code',
  'Legacy password controls are disabled.': 'Les mots de passe sont desactives.',
  'Passwordless Session': 'Session sans mot de passe',
  'Close Account': 'Fermer le compte',
  'Storefront Architecture': 'Configuration boutique',
  'Store Pickup Address Configuration': 'Adresse de retrait boutique',
  'Identity Validation': 'Verification identite',
  'Verified Identity': 'Identite verifiee',
  'Your identity matrix has been fully synchronized and validated.': 'Votre identite a ete verifiee et validee.',
  'Validation in Progress': 'Verification en cours',
  'Our node controllers are reviewing your credentials.': 'Notre equipe examine vos documents.',
  'Credential Type': 'Type de document',
  'National Identification': 'Carte nationale d identite',
  'Global Passport': 'Passeport',
  'Driver Authorization': 'Permis de conduire',
  'Biometric Scans': 'Documents d identite',
  'Primary Face (Front)': 'Face avant',
  'Secondary Face (Back)': 'Face arriere',
  'Initialize Scan': 'Televerser',
  'Followed Vendors': 'Vendeurs suivis',
  'No Followed Vendors': 'Aucun vendeur suivi',
  'Store Audience': 'Audience boutique',
  'No Followers Yet': 'Aucun abonne',
  'Signal Parameters': 'Parametres',
  'Saved Items': 'Articles sauvegardes',
  'Your wishlist is empty': 'Votre liste de favoris est vide',
  'Order not found': 'Commande introuvable',
  'Shipment activity': 'Activite expedition',
  'Sales History': 'Historique de commande',
  'No extra note for this update.': 'Aucune note pour cette mise a jour.',
  'No carrier updates yet': 'Aucune mise a jour du transporteur',
  'No carrier assigned yet': 'Aucun transporteur assigne',
  'Open dispute': 'Ouvrir un litige',
  'Describe the issue so our team can review.': 'Decrivez le probleme afin que notre equipe puisse examiner.',
  'Reason': 'Motif',
  'Asset not manifested': 'Article non recu',
  'Registry mismatch': 'Article non conforme',
  'Structural defects': 'Article defectueux',
  'Protocol violation': 'Autre probleme',
  'Comment': 'Commentaire',
  'Leave a review': 'Laisser un avis',
  'Request Submitted': 'Demande envoyee',
  'Withdraw Funds': 'Retirer des fonds',
  'AMOUNT (XAF)': 'MONTANT (XAF)',
  'SELECT METHOD': 'CHOISIR LA METHODE',
  'RECIPIENT DETAILS': 'DETAILS DU BENEFICIAIRE',
  'COUNTRY': 'PAYS',
  'REVIEW & CONFIRM': 'VERIFIER ET CONFIRMER',
  'Your earnings': 'Vos revenus',
  'Your Earnings': 'Vos revenus',
  'Pickup': 'Retrait',
  'Drop-off': 'Livraison',
  'Pickup Location': 'Lieu de retrait',
  'Delivery Destination': 'Destination',
  'Recipient': 'Destinataire',
  'Delivery Notes': 'Notes de livraison',
  'Qty': 'Qte',
  'New Shipment Status': 'Nouveau statut d expedition',
  'Pending Approval': 'Approbation en attente',
  'Assigned Courier': 'Coursier assigne',
  'Picked Up': 'Recupere',
  'In Transit': 'En route',
  'Out For Delivery': 'En livraison',
  'Delivered Successfully': 'Livre avec succes',
  'Delivery Failed': 'Livraison echouee',
  'Operational Note': 'Note operationnelle',
  'Select failure reason': 'Choisir le motif d echec',
  'Update Shipment': 'Mettre a jour l expedition',
  'New Message': 'Nouveau message',
  'Added to Stack': 'Ajoute au panier',
  'Chats': 'Discussions',
  'Story reply': 'Reponse a la story',
  'Video': 'Video',
  'Product': 'Produit',
  'Frequency History': 'Historique',
  'No Order Records': 'Aucune commande',
  'Saved items': 'Articles sauvegardes',
  'No saved items yet': 'Aucun article sauvegarde',
  'Aura Assistant': 'Assistant Aura',
  'Online': 'En ligne',
  'Sort:': 'Trier :',
  'Followed vendors': 'Vendeurs suivis',
  'Select': 'Selectionner',
  'Vendor': 'Vendeur',
  'Price': 'Prix',
  'Rating': 'Note',
  'Featured': 'En vedette',
  'Global Flow': 'Flux global',
  'Total Processed': 'Total traite',
  'Escrow Pool': 'Fonds sequestres',
  'Held Liquidity': 'Liquidite retenue',
  'Entity count': 'Nombre de comptes',
  'Registered Items': 'Elements inscrits',
  'Merchant Base': 'Base vendeurs',
  'Active Stores': 'Boutiques actives',
  'Actives': 'Actifs',
  'Registered Accounts': 'Comptes inscrits',
  'Merchant Queue': 'File vendeurs',
  'Awaiting KYC': 'KYC en attente',
  'Asset Pipeline': 'File produits',
  'Pending Approval': 'Approbation en attente',
  'Global Volume': 'Volume global',
  'Gross Platform Revenue': 'Revenu brut plateforme',
  'Escrow Vault': 'Coffre sequestre',
  'Platform Liquidity': 'Liquidite plateforme',
  'Volume': 'Volume',
  'Marketplace flow': 'Flux marketplace',
  'KYC Queue': 'File KYC',
  'Awaiting review': 'En attente de revision',
  'Escrow': 'Sequestre',
  'Protected funds': 'Fonds proteges',
  'Flow': 'Flux',
  'Review': 'Revision',
  'Vault': 'Coffre',
  'Primary': 'Principal',
  'Warning': 'Alerte',
  'Risk Log': 'Journal risques',
  'Auth Failure Signals': 'Signaux echec connexion',
  'Secure': 'Securise',
  'Secured Nodes': 'Noeuds securises',
  'Nominal': 'Normal',
  'Core Stable': 'Systeme stable',
  'Revenue': 'Revenu',
  'Total Earned': 'Total gagne',
  'Withdrawn': 'Retire',
  'XAF Ready': 'XAF disponible',
  'Pending Delivery': 'Livraison en attente',
  'Total earned': 'Total gagne',
  'Deposit Money': 'Deposer',
  'Withdraw Money': 'Retirer',
  'Transaction History': 'Historique transactions',
  'Real-time transaction history': 'Historique en temps reel',
  'Available Balance': 'Solde disponible',
  'Secure Account': 'Compte securise',
  'Available to spend': 'Disponible',
  'Held in escrow': 'Bloque en sequestre',
  'Successful': 'Reussi',
  'Payments declined': 'Paiements refuses',
  'Recheck payment': 'Verifier paiement',
  'Still processing': 'Traitement en cours',
  'Payment confirmed! Your wallet has been credited.': 'Paiement confirme ! Votre wallet a ete credite.',
  'Payment could not be confirmed.': 'Paiement non confirme.',
  'Could not reach server. Please try again.': 'Serveur inaccessible. Reessayez.',
  'Could not reach server. Try again shortly.': 'Serveur inaccessible. Reessayez bientot.',
  'Phone number is required.': 'Numero de telephone requis.',
  'Minimum deposit is': 'Depot minimum :',
  'Product sales XAF': 'Ventes produits XAF',
  'Escrow protection XAF': 'Protection sequestre XAF',
  'Mobile money XAF': 'Mobile money XAF',
  'Future revenue XAF': 'Revenus futurs XAF',
  'Commission': 'Commission',
  'Escrow fees': 'Frais sequestre',
  'Collection fees': 'Frais de collecte',
  'Subscriptions': 'Abonnements',
  'Recover': 'Recuperer',
  'Order total': 'Total commande',
  'Order Summary': 'Resume commande',
  'Cart Subtotal': 'Sous-total panier',
  'Final Total': 'Total final',
  'Delivery Details': 'Details livraison',
  'Confirm your address, logistics partner, and payment method.': 'Confirmez votre adresse, partenaire logistique et methode de paiement.',
  'Consignee Name': 'Nom du destinataire',
  'Comms Protocol (Phone)': 'Telephone',
  'Handshake Email': 'E-mail',
  'Delivery Quartier (Zone)': 'Quartier de livraison',
  'Precise Landing Details (Build/Street No.)': 'Adresse precise',
  'Logistics Partner': 'Partenaire logistique',
  'Payment Strategy': 'Methode de paiement',
  'Delivery Option': 'Option de livraison',
  'Vendor managed': 'Gere par le vendeur',
  'No logistics fee': 'Aucun frais logistique',
  'Place order': 'Commander',
  'Terminate checkout': 'Quitter le paiement',
  'Your balance': 'Votre solde',
  'Remove': 'Retirer',
  'Qty': 'Qte',
  'Quantity': 'Quantite',
  'Variant': 'Variante',
  'Color': 'Couleur',
  'Size': 'Taille',
  'Case': 'Boitier',
  'Pan Count': 'Nombre de godets',
  'Order data': 'Donnees commande',
  'Guest': 'Invite',
  'No email': 'Pas d e-mail',
  'No phone': 'Pas de telephone',
  'Payment pending': 'Paiement en attente',
  'Awaiting payment': 'Paiement attendu',
  'Awaiting gateway confirmation.': 'Confirmation du paiement en attente.',
  'Gateway payment confirmed.': 'Paiement confirme.',
  'Pay on delivery': 'Paiement a la livraison',
  'Refund pending': 'Remboursement en attente',
  'Refunded to wallet': 'Rembourse dans le wallet',
  'Wallet credited': 'Wallet credite',
  'Cancel order': 'Annuler la commande',
  'Cancellation window': 'Delai d annulation',
  'Cancel request': 'Demande d annulation',
  'Open dispute': 'Ouvrir un litige',
  'Verify delivery': 'Verifier la livraison',
  'Release escrow': 'Liberer le sequestre',
  'Mark shipped': 'Marquer expedie',
  'Mark delivered': 'Marquer livre',
  'Shipment activity': 'Activite expedition',
  'Cargo items': 'Articles',
  'Tracking code': 'Code de suivi',
  'No tracking yet': 'Aucun suivi',
  'Awaiting logistics tracking': 'Suivi logistique en attente',
  'Packed': 'Emballe',
  'Ready for pickup': 'Pret pour retrait',
  'In transit': 'En route',
  'Out for delivery': 'En livraison',
  'Customer absent': 'Client absent',
  'Wrong address': 'Adresse incorrecte',
  'Refused': 'Refuse',
  'Returned': 'Retourne',
  'Report failed delivery': 'Signaler echec livraison',
  'Mark picked up': 'Marquer recupere',
  'Mark in transit': 'Marquer en route',
  'Mark returned': 'Marquer retourne',
  'Failed delivery reporting': 'Signalement echec livraison',
  'Reason selector': 'Choix du motif',
  'Notes field': 'Champ notes',
  'Retry scheduling': 'Planification nouvel essai',
  'Service zone setup': 'Zones de service',
  'Rider details': 'Details livreur',
  'Vehicle info': 'Info vehicule',
  'Availability toggle': 'Disponibilite',
  'New pickup request': 'Nouvelle demande de retrait',
  'Order assigned': 'Commande assignee',
  'Delivery confirmed': 'Livraison confirmee',
  'Payment released': 'Paiement libere',
  'Dispute involving delivery': 'Litige livraison',
  'Public Ratings': 'Avis publics',
  'Reputation Hub': 'Reputation',
  'Recent Feed': 'Activite recente',
  'Low Scores': 'Notes basses',
  'Resolved': 'Resolus',
  'Top Tier': 'Meilleurs',
  'Closed': 'Fermes',
  'Total Reviews': 'Total avis',
  'Rate': 'Taux',
  'Yield': 'Score',
  'Vendor Dashboard': 'Tableau vendeur',
  'Aura Stories Manager': 'Gestion stories',
  'Share updates & engage with your followers': 'Partagez des nouvelles avec vos abonnes',
  'Store management': 'Gestion boutique',
  'Product management': 'Gestion produits',
  'Submit for approval': 'Soumettre pour approbation',
  'Approval status': 'Statut approbation',
  'Hidden': 'Masque',
  'Rejected': 'Rejete',
  'Vacation mode': 'Mode pause',
  'Store visibility': 'Visibilite boutique',
  'Policy acceptance': 'Acceptation politique',
  'Best-selling products': 'Produits les plus vendus',
  'Date range': 'Plage de dates',
  'Incoming order list': 'Liste commandes entrantes',
  'Pack': 'Emballer',
  'Approve refund': 'Approuver remboursement',
  'Payout history': 'Historique paiements',
  'Fee breakdown': 'Details des frais',
  'New order alert': 'Alerte nouvelle commande',
  'KYC approved': 'KYC approuve',
  'KYC rejected': 'KYC rejete',
  'Payout processed': 'Paiement traite',
  'User management': 'Gestion utilisateurs',
  'Account status': 'Statut compte',
  'Suspended': 'Suspendu',
  'Deleted': 'Supprime',
  'Manual intervention': 'Intervention manuelle',
  'Force release': 'Liberation forcee',
  'Partial refund': 'Remboursement partiel',
  'Decision': 'Decision',
  'Evidence': 'Preuve',
  'Evidence upload': 'Televerser preuve',
  'Resolution notes': 'Notes resolution',
  'Product approvals': 'Approbations produits',
  'Approval queue': 'File approbation',
  'Rejection reason': 'Motif rejet',
  'Edit product': 'Modifier produit',
  'Hide product': 'Masquer produit',
  'Finance': 'Finance',
  'Withdrawal approval queue': 'File retraits',
  'Commission configuration': 'Configuration commissions',
  'Payout rules': 'Regles paiements',
  'Gateway settings': 'Parametres passerelle',
  'Broadcast notification': 'Notification diffusee',
  'Notification composer': 'Compositeur notification',
  'No products in your store': 'Aucun produit dans votre boutique',
  'Your cart is empty': 'Votre panier est vide',
  'No messages': 'Aucun message',
  'No notifications': 'Aucune notification',
  'No results found': 'Aucun resultat',
  'Session expired': 'Session expiree',
  'Network offline': 'Reseau hors ligne',
  'Offline mode': 'Mode hors ligne',
  'File too large': 'Fichier trop lourd',
  'Unsupported file type': 'Type de fichier non supporte',
  'This field is required': 'Ce champ est requis',
  'Please enter a valid email': 'Entrez un e-mail valide',
  'Invalid OTP': 'OTP invalide',
  'OTP expired, please request a new code': 'OTP expire, demandez un nouveau code',
  'Withdrawal limit exceeded': 'Limite de retrait depassee',
  'Order cannot be cancelled': 'Commande non annulable',
  'Encryption protocol v3.1 active': 'Protocole de chiffrement v3.1 actif',
  'Approve Payment': 'Approuver le paiement',
  'Aura Escrow Protection': 'Protection escrow Aura',
  'Secure funds until delivery confirmation, including mobile money checkout': 'Fonds securises jusqu a confirmation de livraison, y compris mobile money',
  'Collection Number': 'Numero de collecte',
  'Currency': 'Devise',
  'LOCKED': 'VERROUILLE',
  'Review Order': 'Verifier commande',
  'Check delivery, payment, and totals before placing the order.': 'Verifiez livraison, paiement et total avant de commander.',
  'Authorized Consignee': 'Destinataire autorise',
  'Delivery Assigned': 'Livraison assignee',
  'By executing this order, payment stays pending and is completed on delivery confirmation for test logistics flow.': 'En executant cette commande, le paiement reste en attente et se termine a la confirmation de livraison.',
  'By executing this order, you authorize the platform to hold': 'En executant cette commande, vous autorisez la plateforme a bloquer',
  'in Escrow vault.': 'dans le coffre escrow.',
  "to the vendor's wallet.": 'vers le wallet du vendeur.',
  'No items in checkout': 'Aucun article au paiement',
  'Order Successful': 'Commande reussie',
  'Your order has been placed and is being prepared for delivery.': 'Votre commande est placee et en preparation pour la livraison.',
  'No zones found': 'Aucune zone trouvee',
  'Logistics Intelligence': 'Intelligence logistique',
  'Operational Analytics': 'Analyses operationnelles',
  'Shipment Flux': 'Flux expeditions',
  'Daily Volume Trends': 'Tendances journalieres',
  'Peak Pulse': 'Pic activite',
  'Normal Range': 'Plage normale',
  'Regional Efficiency': 'Efficacite regionale',
  'Transit Time Accuracy': 'Precision temps transit',
  'Automated Insights': 'Insights automatiques',
  'Recent orders first': 'Commandes recentes d abord',
  'Recent assignments first': 'Affectations recentes d abord',
  'All statuses': 'Tous les statuts',
  'In transit (active)': 'En route (actif)',
  'Assigned': 'Assigne',
  'Picked up': 'Recupere',
  'Cancelled / vendor': 'Annule / vendeur',
  'Items': 'Articles',
  'Destination': 'Destination',
  'Order placed': 'Commande placee',
  'Your fee': 'Votre frais',
  'Open': 'Ouvrir',
  'Get started': 'Commencer',
  'Message hub': 'Messages',
  'Relay nodes': 'Noeuds relais',
  'My Wallet': 'Mon wallet',
  'Mobile money deposit': 'Depot mobile money',
  'Deposit gateway': 'Passerelle depot',
  'Deposit amount (XAF)': 'Montant depot (XAF)',
  'Amount requested': 'Montant demande',
  'Account phone': 'Telephone du compte',
  'Country': 'Pays',
  'Eversend deposits require at least 500 XAF.': 'Les depots Eversend exigent au moins 500 XAF.',
  'Do not close this window': 'Ne fermez pas cette fenetre',
  'Manifests Ledger': 'Registre manifestes',
  'Active Assignments': 'Affectations actives',
  'Receiver': 'Recepteur',
  'Route': 'Route',
  'Date': 'Date',
  'Previous': 'Precedent',
  'Security Audit': 'Audit securite',
  'Decrypting Stream...': 'Dechiffrement du flux...',
  'Mutation Payload': 'Donnees mutation',
  'No System Mutations Recorded': 'Aucune mutation systeme',
  'Case Inspection': 'Inspection dossier',
  'Evidence Void': 'Aucune preuve',
  'Synchronizing Items...': 'Synchronisation...',
  'Operational Proof Log': 'Journal preuve operationnelle',
  'Verified Signatory': 'Signataire verifie',
  'Dispute Tribunal': 'Tribunal litiges',
  'Arbitration Master': 'Arbitrage',
  'Arbitration Queue Synchronized': 'File arbitrage synchronisee',
  'Asset Value': 'Valeur article',
  'No Active Arbitration Items': 'Aucun litige actif',
  'Intelligence Matrix': 'Matrice intelligence',
  'Global Platform Insight': 'Vue plateforme globale',
  'Revenue Velocity (30D)': 'Vitesse revenu (30J)',
  'Real-Time Market Pulse': 'Pouls marche temps reel',
  'Inventory Health': 'Etat inventaire',
  'Stock Alerts': 'Alertes stock',
  'Asset Conversion Performance': 'Performance conversion produits',
  'Sold': 'Vendu',
  'Official Transaction Receipt': 'Recu officiel transaction',
  'Vendor Wallet': 'Wallet vendeur',
  'Product Details': 'Details produit',
  'Long Description': 'Description longue',
  'Specifications': 'Specifications',
  'Media Assets': 'Medias',
  'Max 5MB per image': 'Max 5 Mo par image',
  'Drop product images here': 'Deposez les images ici',
  'Organization': 'Organisation',
  'Tags': 'Etiquettes',
  'Featured Item': 'Article en vedette',
  'Boost visibility': 'Booster la visibilite',
  'No orders found.': 'Aucune commande trouvee.',
  'Sales Analytics': 'Analyse ventes',
  'Revenue Over Time (30D)': 'Revenu sur 30J',
  'Revenue Stream': 'Flux revenu',
  'No sales data available yet.': 'Aucune donnee de vente.',
  'Top Selling Products': 'Meilleures ventes',
  'Settlement Amount': 'Montant reglement',
  'View All': 'Tout voir',
  'Queue Control Management': 'Gestion file de controle',
  'Global Governance Active': 'Gouvernance globale active',
  'No pending nodes in the synchronization queue.': 'Aucun element en attente.',
  'Ident Node': 'Identite',
  'Descriptor': 'Description',
  'Protocol State': 'Etat protocole',
  'Governance': 'Gouvernance',
  'Merchant Node': 'Vendeur',
  'Edit Product': 'Modifier produit',
  'Product Type': 'Type produit',
  'Configure Variations': 'Configurer variantes',
  'Attribute Name': 'Nom attribut',
  'Options': 'Options',
  'Combination': 'Combinaison',
  'Price (XAF)': 'Prix (XAF)',
  'Stock': 'Stock',
  'Transit Protocol': 'Protocole transit',
  'Network Master': 'Reseau maitre',
  'Synchronized Fulfillment Matrix': 'Matrice fulfillment synchronisee',
  'Asset Transit ID': 'ID transit',
  'Destination Topology': 'Topologie destination',
  'Assigned Network Center': 'Centre reseau assigne',
  'Operational Tariff': 'Tarif operationnel',
  'Geographic Cluster': 'Groupe geographique',
  'Topology State': 'Etat topologie',
  'Zone Identifier': 'Identifiant zone',
  'Topology Type': 'Type topologie',
  'Region / City Cluster': 'Region / ville',
  'Quartier (Sub-Node)': 'Quartier',
  'Parent Cluster': 'Groupe parent',
  'SELECT ROOT NODE': 'CHOISIR NOEUD RACINE',
  'Tariff Calibration Protocol': 'Calibration tarifaire',
  'Inject Operational Price Node': 'Ajouter tarif operationnel',
  'Target Topology Node': 'Zone cible',
  'SELECT QUARTIER NODE': 'CHOISIR QUARTIER',
  'Operational Tariff (XAF)': 'Tarif operationnel (XAF)',
  'Active Network Tariff Grid': 'Grille tarifs active',
  'Topology Sector': 'Secteur',
  'Active Rate': 'Tarif actif',
  'Grid Data Void': 'Aucune donnee',
  'Fulfillment Override': 'Modification expedition',
  'Manual Package Calibration Protocol': 'Calibration manuelle colis',
  'Transit ID Signal': 'Signal ID transit',
  'Manifest Tariff (XAF)': 'Tarif manifeste (XAF)',
  'Network Transmission State': 'Etat transmission',
  'Internal Calibration Log': 'Journal interne',
  'Earnings Intelligence': 'Intelligence revenus',
  'Settlement Manifest 2026': 'Manifeste reglement 2026',
  'Current Cycle': 'Cycle actuel',
  'Archived Cycles': 'Cycles archives',
  'Gross Marketplace Volume': 'Volume brut marketplace',
  'Growth vs Prev': 'Croissance vs precedent',
  'Total Logistics Burn': 'Cout logistique total',
  'OPTIMIZED': 'OPTIMISE',
  'Fuel Index 0.82': 'Indice carburant 0.82',
  'Merchant Items': 'Articles vendeurs',
  'Logistics Partners': 'Partenaires logistiques',
  'Draft': 'Brouillon',
  'Approved / Active': 'Approuve / actif',
  'Disapproved / Archived': 'Refuse / archive',
};

const AUTO_ATTRIBUTE_TRANSLATIONS_FR = {
  ...AUTO_TEXT_TRANSLATIONS_FR,
  'Search products and stores': 'Rechercher produits et boutiques',
  'Search premium products...': 'Rechercher produits premium...',
  'Search by order ID or product': 'Rechercher par commande ou produit',
  'Find anything...': 'Rechercher...',
  'Search users...': 'Rechercher utilisateurs...',
  'Search products...': 'Rechercher produits...',
  'Search orders...': 'Rechercher commandes...',
  'Search vendors...': 'Rechercher vendeurs...',
  'Search transactions...': 'Rechercher transactions...',
  'Search withdrawals...': 'Rechercher retraits...',
  'Search disputes...': 'Rechercher litiges...',
  'Search reviews...': 'Rechercher avis...',
  'Search categories...': 'Rechercher categories...',
  'Search manifests...': 'Rechercher manifestes...',
  'Search shipments...': 'Rechercher expeditions...',
  'Search by customer, product, or order ID': 'Rechercher par client, produit ou ID commande',
  'Search by name, email, or phone': 'Rechercher par nom, e-mail ou telephone',
  'Search by reference, user, or order': 'Rechercher par reference, utilisateur ou commande',
  'Enter override justification...': 'Entrez la justification...',
  'Delivery notes or nearest landmark': 'Notes de livraison ou repere proche',
  'Product title': 'Titre du produit',
  'Product description': 'Description du produit',
  'Store description': 'Description boutique',
  'Pickup address description': 'Description adresse de retrait',
  'Phone number': 'Numero de telephone',
  'Email address': 'Adresse e-mail',
  'Full name': 'Nom complet',
  'Amount': 'Montant',
  'Reference': 'Reference',
  'Reason': 'Motif',
  'Comment': 'Commentaire',
  'Notes': 'Notes',
  'Message': 'Message',
  'Write a message': 'Ecrire un message',
  'Find anything': 'Rechercher',
  'Messages': 'Messages',
  'Wallet balance': 'Solde wallet',
};

const shouldTranslateNodeParent = (parent) => {
  if (!parent || parent.nodeType !== 1) return false;
  const tag = parent.tagName?.toLowerCase();
  if (['script', 'style', 'textarea', 'code', 'pre', 'noscript'].includes(tag)) return false;
  return !parent.closest('[translate="no"], .notranslate, [data-no-translate], [data-aura-no-translate]');
};

const shouldTranslateElement = (element) => {
  if (!element || element.nodeType !== 1) return false;
  const tag = element.tagName?.toLowerCase();
  if (['script', 'style', 'code', 'pre', 'noscript'].includes(tag)) return false;
  return !element.closest('[translate="no"], .notranslate, [data-no-translate], [data-aura-no-translate]');
};

const preserveOuterSpacing = (text, translated) => {
  const leading = text.match(/^\s*/)?.[0] || '';
  const trailing = text.match(/\s*$/)?.[0] || '';
  return `${leading}${translated}${trailing}`;
};

const normalizeLanguage = (value) =>
  SUPPORTED_LANGUAGES.some((language) => language.code === value) ? value : 'en';

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: (key, fallback, replacements) => fallback || key,
  label: (value, fallback) => fallback || value,
  languages: SUPPORTED_LANGUAGES,
});

export function LanguageProvider({ children }) {
  const userLanguage = useAuthStore((state) => state.user?.preferred_language);
  const [language, setLanguageState] = useState(readStoredLanguage);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (!stored && userLanguage) {
      setLanguageState(normalizeLanguage(userLanguage));
    }
  }, [userLanguage]);

  useEffect(() => {
    if (typeof document === 'undefined') return;
    document.documentElement.lang = language;
    try {
      window.localStorage.setItem(STORAGE_KEY, language);
      document.cookie = `${STORAGE_KEY}=${language}; path=/; max-age=31536000; SameSite=Lax`;
    } catch {}
  }, [language]);

  useEffect(() => {
    if (typeof window === 'undefined' || typeof document === 'undefined') return undefined;

    const textMap = language === 'fr' ? AUTO_TEXT_TRANSLATIONS_FR : null;
    const attributeMap = language === 'fr' ? AUTO_ATTRIBUTE_TRANSLATIONS_FR : null;
    let frame = null;

    const translateTextNode = (node) => {
      if (!shouldTranslateNodeParent(node.parentElement)) return;
      const original = node.__auraOriginalText || node.nodeValue;
      if (!node.__auraOriginalText) node.__auraOriginalText = original;

      if (!textMap) {
        if (node.nodeValue !== original) node.nodeValue = original;
        return;
      }

      const key = String(original || '').trim();
      const translated = textMap[key];
      if (translated) node.nodeValue = preserveOuterSpacing(original, translated);
    };

    const translateAttributes = (element) => {
      if (!element || element.nodeType !== 1) return;
      if (!shouldTranslateElement(element)) return;

      ['placeholder', 'title', 'aria-label'].forEach((attribute) => {
        if (!element.hasAttribute(attribute)) return;
        const originalAttribute = `data-aura-original-${attribute}`;
        const original = element.getAttribute(originalAttribute) || element.getAttribute(attribute);
        if (!element.hasAttribute(originalAttribute)) {
          element.setAttribute(originalAttribute, original);
        }

        if (!attributeMap) {
          if (element.getAttribute(attribute) !== original) element.setAttribute(attribute, original);
          return;
        }

        const translated = attributeMap[String(original || '').trim()];
        if (translated) element.setAttribute(attribute, translated);
      });
    };

    const scan = (root = document.body) => {
      if (!root) return;
      if (root.nodeType === Node.TEXT_NODE) {
        translateTextNode(root);
        return;
      }

      if (root.nodeType === Node.ELEMENT_NODE) {
        translateAttributes(root);
      }

      const walker = document.createTreeWalker(
        root,
        NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT,
        {
          acceptNode(node) {
            if (node.nodeType === Node.TEXT_NODE) {
              return node.nodeValue?.trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
            }
            return NodeFilter.FILTER_ACCEPT;
          },
        }
      );

      let current = walker.currentNode;
      while (current) {
        if (current.nodeType === Node.TEXT_NODE) {
          translateTextNode(current);
        } else if (current.nodeType === Node.ELEMENT_NODE) {
          translateAttributes(current);
        }
        current = walker.nextNode();
      }
    };

    const scheduleScan = (root) => {
      if (frame) window.cancelAnimationFrame(frame);
      frame = window.requestAnimationFrame(() => {
        scan(root || document.body);
        frame = null;
      });
    };

    scheduleScan(document.body);

    const observer = new MutationObserver((mutations) => {
      const root = mutations.find((mutation) => mutation.target)?.target || document.body;
      scheduleScan(root.nodeType === Node.ELEMENT_NODE ? root : root.parentElement);
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: true,
      attributes: true,
      attributeFilter: ['placeholder', 'title', 'aria-label'],
    });

    return () => {
      if (frame) window.cancelAnimationFrame(frame);
      observer.disconnect();
    };
  }, [language]);

  const value = useMemo(() => ({
    language,
    languages: SUPPORTED_LANGUAGES,
    setLanguage: (nextLanguage, options = {}) => {
      const normalized = normalizeLanguage(nextLanguage);
      setLanguageState(normalized);
      if (typeof document !== 'undefined') {
        document.documentElement.lang = normalized;
      }
      try {
        window.localStorage.setItem(STORAGE_KEY, normalized);
        document.cookie = `${STORAGE_KEY}=${normalized}; path=/; max-age=31536000; SameSite=Lax`;
        window.dispatchEvent(new CustomEvent('aura:language-change', { detail: { language: normalized } }));
      } catch {}
      if (options.reload && normalized !== language && typeof window !== 'undefined') {
        window.setTimeout(() => {
          window.location.reload();
        }, 120);
      }
    },
    t: (key, fallback, replacements = {}) => {
      const template = translations[language]?.[key] || translations.en[key] || fallback || key;
      return Object.entries(replacements).reduce(
        (text, [name, value]) => text.split(`{${name}}`).join(String(value)),
        String(template)
      );
    },
    label: (value, fallback) => {
      const original = fallback || value;
      const key = `label.${labelSlug(value)}`;
      return translations[language]?.[key] || translations.en[key] || original;
    },
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
